### ISSUE TITLE
Responsivität der Admin Seiten

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#100]
Die einzelnen Panels im Admin-Bereich müssen responsiv gestylet werden.

Vor allem im Vordergrund: Nutzer, Gruppen, Feedback, Kategorien & Marginalen.

**Comment by techotline** [comment]
@BillyTheKing Nachdem Alexis Deine PR's übernommen und zusammengeführt hat, musste ich mir unbedingt das UI bei Staging ansehen. Dabei ließ sich feststellen, dass sich zwischenzeitlich neue Fehler eingeschlichen haben. 

Teilweise sind Buttons abgeschnitten oder überlappen mit anderen Elementen. Sieh selbst! 

![image](https://github.com/lotta-schule/web/assets/153733311/19700c82-4d21-4810-9df9-88a6cbaf3c7b)
![image](https://github.com/lotta-schule/web/assets/153733311/2951baf7-b027-410f-b655-19984b2c59ac)
![image](https://github.com/lotta-schule/web/assets/153733311/ec623b56-b6e8-45c4-b6ca-a127ba7e0a88)

**Comment by ptitmouton** [comment]
Fix in #123
