### ISSUE TITLE
[Feature]: 'Meine Beiträge' soll Gruppen anzeigen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#104]
"Meine Beiträge"

### Vorschlag

**Idee:** Es sollte eine Funktion implementiert werden, die es allen Nutzern ermöglicht, eine Übersicht über ihre verfassten Beiträge zu erhalten und gleichzeitig die Zielgruppe oder Sichtbarkeit dieser Beiträge einzusehen

Grund: Übersichtlichkeit über Beiträge und deren Sichtbarkeit
Klickweg: Mein Profil > "Meine Beiträge"

### Beschreibung

So könnte es simpel gelöst werden: 

<img width="1244" alt="001-Meine-Beitraege-2023" src="https://github.com/lotta-schule/web/assets/153733311/bc32424a-cca8-4529-8bc4-4c130bddb2a6">

**Comment by techotline** [comment]
vergleichbar #96

**Comment by ptitmouton** [comment]
Gehört zu #96
