### ISSUE TITLE
[Bug]: UserMenu lässt sich auf iPad nur umständlich öffnen

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#106]
### Bug-Beschreibung

Möchte man auf einem iPad das Pop-Up-Menü „Mein Profil“ öffnen, gelingt das nur , wenn man die äußerste Ecke des Button trifft. Vgl Bildschirmaufnahme. @

https://github.com/lotta-schule/web/assets/143288974/905c3e5c-66db-4294-bd52-45ee0bbf79c9

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/

### Gerätekategorie

Tablet (iPad, Galaxy Tab o.ä.)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
@wie0815 dein video wird nicht angezeigt

**Comment by techotline** [comment]
> @wie0815 dein video wird nicht angezeigt

Ich kann es abspielen ... @BillyTheKing

**Comment by BillyTheKing** [comment]
@wie0815 die Bildschirmaufnahme hilft nicht so recht, wenn man den Ort des Touchs nicht sieht. Vielleicht Assistent Touch fürs nächste mal verwenden.
Ich konnte den Fehler jedoch nachstellen und es scheint sich für mich auf den ersten Blick um ein Styling Problem zu handeln. 

@BillyTheKing  **Mittlere bis geringe Prio.**

**Comment by techotline** [comment]
selbiges Problem in der mobil-view in Admin-Bereich -> Marginalen -> Marginale erstellen (Safari)

Systemdaten: User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2
Mobile/15E148 Safari/604.1
Platform: iPhone Screen: 393x852
Window: 393X659
DevicePixelRatio: 3
DeviceOrientation: portrait-primary

**Comment by BillyTheKing** [comment]
@techotline hierzu haben wir bereits ein Ticket. #100

**Comment by techotline** [comment]
> @techotline hierzu haben wir bereits ein Ticket. #100 

Ja, sorry!

**Comment by BillyTheKing** [comment]
Alles gut. Deshalb der Hinweis.

**Comment by ptitmouton** [comment]
Irgendwann bekommen wir es vielleicht hin, hübsche, performante, barrierefreie, auf allen Geräten funktionierende Popups an die richtige Stelle zu rendern ...
