### ISSUE TITLE
Admin-Bereich: Nach "Gruppe" filtern ergänzen.

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#107]
### Bereich

Administrationsbereich (inkl. "Feedback")

### Verhalten

Verhalten

### Problem

Haben sich Nutzer ein Profil erstellt und KEINE Gruppenschlüssel eingegeben, findet man den Nutzer nicht, ohne dessen Namen. 

### Beschreibung

Es wäre sehr gut, wenn man der Auswahl von Gruppen "**Ohne Gruppe**" hinzufügen kann.
<img width="663" alt="Bildschirmfoto 2024-01-07 um 21 02 14" src="https://github.com/lotta-schule/web/assets/143288974/3f440898-66dc-49ae-9403-2461b0b199e2">
... um beispielsweise einen neuen Nutzer per Hand zu einer Gruppe hinzuzufügen.

**Comment by techotline** [comment]
@ptitmouton Wie lange könnte es dauern, dieses Ticket zu bearbeiten?

Kann bis zum Release von 4.2 bewerkstelligt werden?

**Comment by ptitmouton** [comment]
Ich denke nicht dass es was wird, hab's aber vorerst für 4.2 eingetaktet gelassen. Ich kann auch gerade noch nicht genau abschätzen wie aufwendig das wird. In jedem Fall wird es eine Anpassung am Core geben müssen. Falls wir doch noch Zeit über und der Rest erledigt sein sollte wird's noch mit reingenommen. Damit rechnen würde ich aber nicht.
