### ISSUE TITLE
[Feature]: Warnung bei der Eingabe von Einschreibeschlüsseln, wenn diese nicht existent sind

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#108]
### Bereich

Nutzerprofil

### Verhalten

Verhalten

### Problem

Oft werden "Einschreibeschlüssel" falsch eingegeben (z.B. durch schusselige Tippfehler). Der Nutzer wundert sich, warum nach der Eingabe von Einschreibeschlüsseln nicht die erhofften Kategorien bzw. Beiträge sichtbar werden. 

### Beschreibung

Denkbar ist ein Hinweis: "Dieser  Einschreibeschlüssel existiert nicht. Prüfen Sie Ihre Eingabe."

**Comment by BillyTheKing** [comment]
@techotline Wir hatten das Thema diesbezüglich schon mal intern diskutiert. Wir möchten umgehen, dass dadurch eine Sicherheitslücke entsteht, da Nutzer so die Möglichkeit erhalten, unendliche Versuche vorzunehmen den richtigen Gruppenschlüssel zu erraten und somit eine Bestätigung erhielten, dass ihr Versuch nicht erfolgreich war.

**Comment by techotline** [comment]
> @techotline Wir hatten das Thema diesbezüglich schon mal intern diskutiert. Wir möchten umgehen, dass dadurch eine Sicherheitslücke entsteht, da Nutzer so die Möglichkeit erhalten, unendliche Versuche vorzunehmen den richtigen Gruppenschlüssel zu erraten und somit eine Bestätigung erhielten, dass ihr Versuch nicht erfolgreich war.

Guter Punkt! Ich kann die Gründe nachvollziehen und denke, wer Lesen kann, dem gelingt die erfolgreiche Eingabe eines Schlüssels.
