### ISSUE TITLE
[Feature]: mobil view: Touch auf Profilbild in Beitragsvorschau sollen Nutzernamen anzeigen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#109]
### Bereich

Beitragsseite

### Verhalten

Verhalten

### Problem

Berührt man auf mobil view ein Profilbild bspw. die Autoren in der Beitragsvorschau wird der jeweilige Nutzername nicht mehr angezeigt.

### Beschreibung

Der Nutzername wird derzeit nur auf Desktopgeräten als Hover angezeigt und sollte mobil auch wieder sichtbar sein.

**Comment by BillyTheKing** [comment]
@techotline Dazu haben wir uns schon ein neues Konzept überlegt. Es besteht auch schon ein Ticket, welches noch zu GitHub migriert werden muss.

**Comment by techotline** [comment]
#112
