### ISSUE TITLE
Unbekannte Lotta-Instanz: Statt 404-Fehlerseite gibt der Server einen 500er aus

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#111]
Übernimmt man die URL einer vorhandenen Domain bzw. den Namen eines Lottas, findet eine Weiterleitung zu dem gesuchten Lotta statt.

Bisher erschien ein Informationsfenster "Seite nicht gefunden", wenn die entsprechende Lotta-Adresse nicht erreichbar ist oder sich in der Adressleiste vertippt wurde. ![image](https://github.com/lotta-schule/web/assets/153733311/0cb2a0f5-2a3b-4bd2-aebf-55edf49887e7)

Aktuell wird das mit "Internal Server Error" ersetzt.

**Comment by techotline** [comment]
@ptitmouton

**Comment by techotline** [comment]
@ptitmouton wird der bugfix mit dem nächsten Deployment ausgeliefert? screen set aktuell noch nicht erreichbar.

**Comment by ptitmouton** [comment]
Kommt in 4.2
