### ISSUE TITLE
Tooltip für Avatare und Tags

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#112]
Beim Hovern (Desktop) und Antippen (Mobil) sollte sich ein Dialog mit zusätzlichen Infos öffnen:
1) Avatare: Anzeige des Nicknames & zugehöriger Gruppen, sowie möglicher Beiträge in denen der Nutzer Autor ist
2) Tags: Anzeige weiterer Beiträge welche mit selbigem Tag versehen sind

MockUps siehe [GitLab](https://gitlab.com/lotta-schule/web-client/-/issues/911/)

**Comment by techotline** [comment]
@BillyTheKing Betrifft Tooltip für Tags: wird dann diese Erweiterung "WEITERE BEITRÄGE" nicht überflüssig, der ja sowieso nur bei registrierten Nutzern angezeigt wird? 

Wenn ein Tag verwendet, wird dieser Bereich automatisch dem Beitrag ergänzt: 
<img width="1178" alt="Bildschirmfoto 2024-01-10 um 21 31 49" src="https://github.com/lotta-schule/web/assets/153733311/ef1173a8-07be-46be-8ff8-bf240590b680">
oder mit anhängenden Beiträgen: 
<img width="1248" alt="Bildschirmfoto 2024-01-10 um 21 32 08" src="https://github.com/lotta-schule/web/assets/153733311/0b84bad1-02ca-4586-95e9-d16416a5f4d8">

**Comment by ptitmouton** [comment]
Wollen wir den Bereich 'weitere Beiträge' behalten oder nicht?

Eigentlich gefällt mir dass weitere Beiträge gut sichtbar aufgeführt werden. 

Hat @wie0815 eine Meinung?

**Comment by techotline** [comment]
@ptitmouton Tags sind aktuell nur produktiv, wenn ein Nutzer angemeldet ist, weil dann mithilfe der Tags die weiteren Beiträge gezeigt werden können. Ist das also ein Bug, dass dem Tag anhängende Beiträge nicht angezeigt werden, wenn ein Nutzer abgemeldet ist?

**Comment by ptitmouton** [comment]
Mir ist nicht bekannt dass wir das nur für angemeldete Nutzer beschränkt hätten, und ein schneller Blick in den Code zeigt das auch nicht. 

Wenn es wirklich so ist dass 'ähnliche Beiträge' vorhanden sind, die für einen nicht angemeldeten Nutzer sichtbar sind, und diese unter dem Beitrag nicht aufgeführt werden, ist es wohl ein Bug.

**Comment by techotline** [comment]
> Mir ist nicht bekannt dass wir das nur für angemeldete Nutzer beschränkt hätten, und ein schneller Blick in den Code zeigt das auch nicht.
> 
> Wenn es wirklich so ist dass 'ähnliche Beiträge' vorhanden sind, die für einen nicht angemeldeten Nutzer sichtbar sind, und diese unter dem Beitrag nicht aufgeführt werden, ist es wohl ein Bug.

#148

**Comment by techotline** [comment]
> Mir ist nicht bekannt dass wir das nur für angemeldete Nutzer beschränkt hätten, und ein schneller Blick in den Code zeigt das auch nicht.
> 
> Wenn es wirklich so ist dass 'ähnliche Beiträge' vorhanden sind, die für einen nicht angemeldeten Nutzer sichtbar sind, und diese unter dem Beitrag nicht aufgeführt werden, ist es wohl ein Bug.

#147

**Comment by techotline** [comment]
> Wollen wir den Bereich 'weitere Beiträge' behalten oder nicht?
> 
> Eigentlich gefällt mir dass weitere Beiträge gut sichtbar aufgeführt werden. 
> 
> Hat @wie0815 eine Meinung?

Ich ziehe meinen "Vorschlag" zurück. Tatsächlich war das eine theoretische Frage, um das Feature neutral zu bewerten. @ptitmouton Dein Argument überzeugt.

**Comment by techotline** [comment]
@ptitmouton Ich denke, dieses Ticket kann geschlossen werden.

**Comment by ptitmouton** [comment]
Das Feature ist noch nicht ganz rund. Für Nutzer werden nur Beiträge angezeigt, bei denen sie *alleinige* Autoren sind und Dialoge schließen sich auf Desktop bei Seitenwechsel noch nicht korrekt

**Comment by wie0815** [comment]
Das Auflisten weiterer Beiträge eines Nutzers finde ich ok., doch eigentlich nicht sinnvoll. Ich denke, dass man eher Interesse an Inhalten hat. Dafür gibt es ja das Taggen. Eure Entscheidung.

**Comment by ptitmouton** [comment]
Das fällt dir echt früh ein @wie0815 ...
