### ISSUE TITLE
Benutzerkonto löschen: Textzeile dupliziert implementiert

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#114]
### Bereich

Nutzerprofil

### Verhalten

Trifft nicht zu

### Problem

Möchte man sein Benutzerkonto löschen, funktioniert dies über das individuelle Menü "Mein Profil". Bestätigt der Nutzer den Button "Benutzerkonto löschen" öffnet sich ein neuer Dialog, wo ihm die nächsten Schritte sowie Konsequenzen seines Vorhabens ausführlich erklärt werden.

### Beschreibung

In diesem Zusammenhang hat sich ein kleiner Fehler eingeschlichen, womit die erste Textzeile doppelt vorhanden ist.

<img width="1245" alt="Bildschirmfoto 2024-01-12 um 18 01 31" src="https://github.com/lotta-schule/web/assets/153733311/d3dd102c-93ff-4cdf-9c50-80a731bd59e7">

**Comment by techotline** [comment]
zudem die Pronomen"deinen", "dich" in moderner Schreibweise ... und alten Schreibstil (jedoch persönlich schöner!) "Du", "Dir"

**Comment by BillyTheKing** [comment]
Nachvollziehbar. Können wir leicht beheben.

Dringlichkeit: Backlog

**Comment by techotline** [comment]
Ich habe weitere signifikante, grammatikalische Fehler gefunden. Dazu folgt ein gesondertes Ticket.
