### ISSUE TITLE
[Feature]: Gruppen Erstellung mit Wahlmöglichkeit der Anzeige von Klarnamen (z.B. im Chat)

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#120]
### Bereich

Nachrichten (inkl. "Meine Beiträge")

### Verhalten

Verhalten

### Problem

Administratoren sehen die Klarnamen im Chat. Andere Gruppen sehen nur den Nickname des Nutzers z.B. im Gruppenchat. Lehrer haben an den Schulen das Problem, dass keine Klarnamen angezeigt werden, in Dialogen die SuS mit korrektem Namen anzusprechen und/oder wissen nicht, wem sie antworten sollen.

### Beschreibung

Es wäre eine sinnvolle Erweiterung, wenn man beim Erstellen von Gruppen ein Häkchen setzten kann, das Mitglieder dieser Gruppe die Klarnamen sehen können. Natürlich wäre es auch sinnvoll, wenn Administratoren Gruppen durch ein Häkchen oder einen An- und Ausschalter diese Entscheidung treffen könnten.

**Comment by ptitmouton** [comment]
Folgende Schritte sind notwendig:

Backend:
[ ] Weitere Option an der Gruppe im Backend speichern und über die Schnittstelle anbieten und bearbeitbar machen
[ ] Beachten dieser Einstellung bei Auslieferung von Klarnamen aus dem Backend

Frontend:
[ ] Einstellen dieser Option im Admin-Bereich möglich machen

Wenn ich nicht ganz falsch liege sollten weitere Anpassungen in keines der Frontends (Web, iOS, Android) notwendig sein da der Klarname schon automatisch in Klammern angezeigt wird falls er vom Backend ausgeliefert wird
