### ISSUE TITLE
/privacy: auf kleinen Bildschirmen lässt sich Seite horizontal ins Leere scrollen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#121]
### Bereich

Etwas ganz anderes

### Verhalten

Aussehen / Design

### Problem

Bei einer inhaltlichen Überprüfung ist aufgefallen, dass die Seite (Beitrag) des Menüpunktes „Datenschutz“ in der seitlichen Navigation die vorgegebenen Grenzen überschreitet und aus dem Seitenformat ausbricht. Anstatt das Format einzuhalten, wird ein Rollbalken ausgeliefert.

Problem aufgefallen: https://recordz.jetzt/privacy

Browser: Safari

User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_3 like Mac OSX) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3
Mobile/15E148 Safari/604.1
Platform: iPhone Screen: 393x852
Window: 393X659
DevicePixelRatio: 3
DeviceOrientation: portrait-primary

Darstellung: ![image](https://github.com/lotta-schule/web/assets/153733311/c76b0008-30ff-4848-8d2a-5e42ce447150)
![image](https://github.com/lotta-schule/web/assets/153733311/346dd239-7a77-43eb-a884-d3f7bd5ee0c7)
![image](https://github.com/lotta-schule/web/assets/153733311/771fea6d-1bb3-4a1d-b530-e2c85405cf04)

### Beschreibung

An dieser Stelle schlage ich vor, diese Seite responsiv zu überarbeiten. @BillyTheKing

**Comment by ptitmouton** [comment]
War selbst auf das Problem gestoßen als ich den neuen Browser eingebaut habe und habe es dort auch schon behoben (Siehe https://github.com/lotta-schule/web/commit/07ab2ccbac7c6194a5dcb24f045a2d1ea5496b45#diff-9219b7ea233832c64a0d22634e29b0da8678c0468905ef789bcbb441b7e92bba)

Das Problem ist in dem Branch also schon gelöst und wird dann mit dem Browser zusammen in `main` gemerged.
