### ISSUE TITLE
[style]: Konfiguration von "Rundungen" in NavBar übernehmen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#124]
### Bereich

Administrationsbereich (inkl. "Feedback")

### Verhalten

Aussehen / Design

### Problem

Möchte man in der Oberfläche seines Lottas sichtbare Anpassungen vornehmen, kann das u.a. über den Dialog "Abstand" zum Seitenfenster und "Rundungen" (Admin -> Darstellung) gelingen. 

Somit werden z.B. alle Buttons dem gewünschten Radius (px) angepasst.  
Das definiert auch die Umrandungen, deren Kantenlänge bzw. den Rahmen der Links (der interaktiven Buttons) in der Hauptnavigation, in der sich aktuell befunden wird. 

_Der border-radius wird aktuell nicht in der grundsätzlichen Komponente der Hauptnavigation übernommen._

<img width="1289" alt="Bildschirmfoto 2024-02-15 um 19 52 59" src="https://github.com/lotta-schule/web/assets/153733311/0dc043dc-27c5-45ba-9007-58d6a3669a3b">

### Beschreibung

Folgende Idee und markanter Vorschlag für Admins: damit ein Lotta eine einheitliche Komponente für sein Aussehen erhält, sollte die Konfigurationsseite "DARSTELLUNG" eine **neue Einstellungsebene für Rahmen in der navbar** erhalten, welche entweder A) das Angebot von "Maße" erweitert oder B) die Relation von Rundungen des Lottas effektiver regelt.

**Comment by techotline** [comment]
@BillyTheKing Hier ist das falsche PR verknüpft ...

**Comment by techotline** [comment]
@ptitmouton Ticket ist bearbeitet, jedoch ist das falsche PR verknüpft ...

**Comment by ptitmouton** [comment]
Fix in #129
