### ISSUE TITLE
iOS: Bsp. Registrierung: Teile der Dialoge werden von UI verdeckt, Buttons in DialogActions sind nicht zu sehen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#127]
### Bug-Beschreibung

Wenn ein neues Benutzerkonto angelegt werden möchte, ruft man über "REGISTRIEREN" ein Pop-up-Fenster auf, in dem vorab persönliche Daten hinterlegt werden. Leider lassen sich die **Buttons "ABBRECHEN" und "REGISTRIEREN"** in der mobile-view nicht anzeigen, da sie abgeschnitten bzw. versteckt sind. 

mobile devices: Bei einem _Seitenzoom von 75%_ können sie wiederum erreicht werden. 
![IMG_7693](https://github.com/lotta-schule/web/assets/153733311/6affce7f-c7d1-4736-80c1-cff4c77e19fd)
![IMG_7695](https://github.com/lotta-schule/web/assets/153733311/a90e12d7-f257-4c55-a6e6-67fce81f4dfc)

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Das ist eine funktionale Einschränkung ich denke wir sollten das für 4.2 noch lösen. 

Ich würde mir das mal in der nächsten Woche ansehen @BillyTheKing

**Comment by ptitmouton** [comment]
Das Problem hat alle Dialog betroffen, die anderen sind nur nicht so hoch geworden.

Ich habe eine passable Lösung gefunden (`-webkit-fill-available` min 100vh-Fallback), bin leider erst später auf `dvh` und Konsorten gestoßen.

https://web.dev/blog/viewport-units

Ich lasse es als zukünftige Referenz mal hier.

**Comment by ptitmouton** [comment]
`-webkit-fill-available` beachtet die Höhe der Safari-Adressleiste nicht korrekt wenn diese nach dem Scrollen im eingeklappten Zustand ist.

**Comment by ptitmouton** [comment]
> Das Problem hat alle Dialog betroffen, die anderen sind nur nicht so hoch geworden.
> 
> Ich habe eine passable Lösung gefunden (`-webkit-fill-available` min 100vh-Fallback), bin leider erst später auf `dvh` und Konsorten gestoßen.
> 
> https://web.dev/blog/viewport-units
> 
> Ich lasse es als zukünftige Referenz mal hier.

Wie schon in meinem Kommentar erwähnt scheint 100dvh das zu tun was `-webkit-fill-available` vorgibt zu tun
