### ISSUE TITLE
[Feature]: Einfache Nutzungsstatistiken im Admin-Bereich zur Verfügung stellen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#131]
### Bereich

Beitragsseite

### Verhalten

Verhalten

### Beschreibung

- A) Aufrufe innerhalb eines Beitrags ersichtlich + B) unter "MEINE BEITRÄGE" anzeigen

**Comment by ptitmouton** [comment]
Etwas, das sich in die Richtung bewegt haben wir für das nächste Release geplant, und es wird vermutlich auch kommen falls sich unsere Technologiewahl bewährt.

Im ersten Schritt wird es nur den Administratoren zur Verfügung stehen, über weitere Schritte kann man diskutieren wenn sich das bewährt hat und wir das auch (noch?) für relevant halten sollten.

Ich übernehme das Ticket @BillyTheKing @techotline
