### ISSUE TITLE
Staging: Responsivität der Admin-Panels für mobile devices

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#134]
@BillyTheKing Nachdem Alexis Deine PR's übernommen und zusammengeführt hat, musste ich mir unbedingt das UI bei Staging ansehen. Dabei ließ sich feststellen, dass sich zwischenzeitlich neue Fehler eingeschlichen haben. 

Teilweise sind Buttons und innenliegender Text abgeschnitten oder überlappen mit anderen Elementen. Sieh selbst! 

- Momentan:

![IMG_1723](https://github.com/lotta-schule/web/assets/153733311/bdd86de8-745a-41d6-ab2f-8a619b734697)
![IMG_1724](https://github.com/lotta-schule/web/assets/153733311/1eeb8fb6-8508-4013-baa6-8777a3c6543b)
![IMG_1938](https://github.com/lotta-schule/web/assets/153733311/bc311932-363c-44c1-b419-259eed033170)
![IMG_1939](https://github.com/lotta-schule/web/assets/153733311/bcb80f49-8f9e-4ba0-be62-5ce8ced4150e)
![IMG_1940](https://github.com/lotta-schule/web/assets/153733311/4d8fa75d-1242-49a2-9dc3-1f3954d9692f)
![IMG_1731](https://github.com/lotta-schule/web/assets/153733311/8544da30-7288-4bd4-b07b-d9ec0e782b53)

- So sollte es aussehen:

![IMG_4630](https://github.com/lotta-schule/web/assets/153733311/8ec6f7e8-a2c1-4d9a-b4ea-4981fcb64519)
![IMG_6827](https://github.com/lotta-schule/web/assets/153733311/b0a0e9b8-5f20-436e-a50a-8ddfb6a2d45f)
![IMG_1942](https://github.com/lotta-schule/web/assets/153733311/be9f84d0-dc12-41c6-a5f1-fbf87c91f191)
![IMG_4620](https://github.com/lotta-schule/web/assets/153733311/ae585e2a-5507-49e3-8eb4-e7e303890f36)

**Comment by ptitmouton** [comment]
@BillyTheKing Mündlich hatten wir ja die neue SplitView-Komponente erstmal nur für die Gruppenansicht abgesprochen, da ich sie jetzt aber ja schon einfach wiederzuverwenden gemacht habe, würde ich sie im Kontext dieses Tickets noch für die Admin-Seiten Kategorien und Marginalen einbauen.

Im gleichen Atemzug würde ich auch gleich die mobilen Toolbars auf den Adminseiten übernehmen, ich übernehme das Ticket also @BillyTheKing 

Darüber hinaus denke ich dass weitere Optimierungen für Mobilnutzer des Adminbereichs darüber hinaus keine Priorität haben sollten, wir haben im Moment wichtigere Sachen auf dem Tisch

**Comment by techotline** [comment]
@ptitmouton Danke! 😊

**Comment by ptitmouton** [comment]
Für die Feedback-Seite habe ich mich doch für die einfachere Variante entschieden, die Abschnitte untereinander statt in einem SplitView anzuzeigen.

**Comment by techotline** [comment]
@ptitmouton Im Allgemeinen gefällt mir die Umsetzung. Exquisite Arbeit! 😎
