### ISSUE TITLE
einheitliche Komponente für Erfolgs- / Fehlermeldungen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#137]
Aussehen / Design

### Problem

Aktuell ersetzt Lotta die Primärfarbe mit einem Grün oder Rot, welches nicht mit dem im UI (Darstellung)  übereinstimmt.

z.B. 
- wenn Formular versendet
- wenn Seite (Beitrag) nicht verfügbar
-  Network Error

Grundsätzlich sollten die Komponenten vorteilhaft eingesetzt werden, wie sie mit der theme-Farbe im admin panel Darstellung verankert sind. 

### Beschreibung

Ich sehe das in Verbindung mit Ticket #125

**Comment by ptitmouton** [comment]
Es gibt schon eine einheitliche Komponente für Fehlermeldungen.

Aufgrund des verschiedenen Scopes von Fehlern ist eine über die Meldung hinausgehende Fehleranzeige nicht möglich (Nachricht anzeigen / ganzen View ersetzen / ...)

Sehe hier entweder eine Dopplung von #125 oder ein wontfix.
