### ISSUE TITLE
Anpassung Datenschutzerklärung

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#150]
Datenschutzerklärung (Stand 08/2019) muss auf den neusten Stand gebracht werden.

**Comment by techotline** [comment]
- "E"insa Gbr ≠ einsA GbR

![image](https://github.com/lotta-schule/web/assets/153733311/094ef9c2-c2b7-42d0-bd68-af67a763162d)

- "Datenschutz" sollte einen Banner erhalten.
