### ISSUE TITLE
Inhaltliche Korrektur > Datenschutzerklärung

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#153]
### Bug-Beschreibung

A) Zwei Abschnitte in DSE projizieren den gleichen Ausdruck:

<img width="1226" alt="Bildschirmfoto 2024-03-14 um 20 57 45" src="https://github.com/lotta-schule/web/assets/153733311/a9357cc3-e191-4c70-b4a9-26f29dcda248">

B) Es sollte ohne Ausnahme die Höflichkeitsform "Sie" verwendet werden. "Dich" muss entsprechend geändert werden.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg.staging.lotta.schule/privacy

### Gerätekategorie

Trifft hier nicht zu

**Comment by techotline** [comment]
Siehe außerdem Kommentar #152

**Comment by ptitmouton** [comment]
Ah mir war nicht klar dass es Ticket zu gibt.
Das nächste Mal gerne in der PR-Beschreibung erwähnen. 

Danke 👌🏼
