### ISSUE TITLE
Theme wird nicht korrekt auf Dialoge angewandt

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#160]
Das Farb-Theme wird nicht korrekt auf das Tooltip, bzw alle Dialoge angewandt.

![Image](https://github.com/lotta-schule/web/assets/11082197/cd394469-bb9a-4caf-a486-a60803ad1ab7)

![Image](https://github.com/lotta-schule/web/assets/11082197/ab8a1e02-c9e2-4baa-8863-b0a374508f4d)

**Comment by ptitmouton** [comment]
Ach du kacke. 
Was haben wir denn da gemacht? 😂

**Comment by ptitmouton** [comment]
@BillyTheKing Ich bin mir nicht ganz sicher das Problem verstanden zu haben.
Du hast das aber im Auge?
Du hast dieses schreckliche Theme bei eberg-staging erstellt um deinen Punkt zu beweisen?
Das Problem sind die Schriftfarben, richtig?

**Comment by techotline** [comment]
> @BillyTheKing Ich bin mir nicht ganz sicher das Problem verstanden zu haben.
> 
> Du hast das aber im Auge?
> 
> Du hast dieses schreckliche Theme bei eberg-staging erstellt um deinen Punkt zu beweisen?
> 
> Das Problem sind die Schriftfarben, richtig?

@ptitmouton ich habe mir den "Konflikt" zwischen den Elementen angesehen. U.a. wird die theme "Hintergrund" (Farbe für den Hintergrund des Inhaltsbereichs) verwendet. Weshalb jedoch eine schwarze Schrift anstatt einer weißen angewendet wird, ist im UI nicht zu erkennen. Anscheinend hat der Dialog keine eindeutige theme für Schrift, der er eigentlich übernehmen müsste (Textfarbe; 'weiß').

![image](https://github.com/lotta-schule/web/assets/153733311/343832b3-19bd-4bfa-8123-cb922540ccdf)

![image](https://github.com/lotta-schule/web/assets/153733311/d836e92b-7a28-4c0e-a0ba-9c8e6a548bbc)

![image](https://github.com/lotta-schule/web/assets/153733311/ca7741a3-0625-452f-b404-e97a2eee396e)
