### ISSUE TITLE
Tableiste im mobilen Nutzermenü lässt sich aus dem Viewport scrollen (nur Staging)

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#162]
### Bug-Beschreibung

[ ] Anordnung der Elemente -> Nutzermenü
[ ] Insbesondere fällt auf, wie das Profilbild über die Tab bar "gerutscht" ist. 

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by techotline** [comment]
![Bug-Menü_1](https://github.com/lotta-schule/web/assets/153733311/05fda8f9-14b8-4ec0-ad61-f27fe7917e6d)
![Bug-Menü_2](https://github.com/lotta-schule/web/assets/153733311/1d7225e8-8fe6-4f47-9ed7-5b26dcd5a816)

**Comment by ptitmouton** [comment]
Fix in https://github.com/lotta-schule/web/pull/171/files
