### ISSUE TITLE
(nur Staging, mobile): Konversation: Toolbar bleibt beim Scrollen "zu tief hängen"

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#163]
### Bug-Beschreibung

Ich verdeutliche den Fehler anhand des Screenshots. Der Nutzer ist beeinträchtigt, weil Bestandteile der split view sich über den Dialog "schieben".

![Dialog-Nachrichten](https://github.com/lotta-schule/web/assets/153733311/7f0d91a2-9200-4de7-8dd8-075a8b93385c)

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Hab vergessen hier und da einer Toolbar zu sagen dass sie den Abstand zur oberen Navigation nicht beachten muss ...
