### ISSUE TITLE
 Randnavigation im mobilen Nutzermenü lässt sich in Marginalen scrollen (nur Staging)

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#165]
### Bug-Beschreibung

![bug-randnavigation](https://github.com/lotta-schule/web/assets/153733311/4b7da62a-7f87-4dfc-8bf4-5b8199f85aa1)

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
Platform: MacIntel
Screen: 1440x900
Window: 1440x795
DevicePixelRatio: 2
DeviceOrientation: landscape-primary

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Bitte erwähne mich nicht bei jedem Ticket in der Beschreibung. Es ist wirklich nicht notwendig und es ist bestimmt kein Trick um zu erreichen dass ich mir ein Ticket schneller ansehe. Ich habe auch so ein Auge auf die Tickets ohne mit noch mehr Benachrichtigungen zugebombt zu werden als sowieso schon

**Comment by techotline** [comment]
Ich nehme es mir zu Herzen. Entschuldige.
