### ISSUE TITLE
[Bug]: Staging: Admin: Statistiken senden Fehler aus

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#168]
### Bug-Beschreibung

![Bug-Statistik_1](https://github.com/lotta-schule/web/assets/153733311/005f7578-7854-497e-bf0f-f35230b0550c)
![Bug-Statistik_2](https://github.com/lotta-schule/web/assets/153733311/fbdf7fda-d87b-48e0-9d91-4ee43dfb521d)

iPadOS:

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)
Version/17.3.1 Safari/605.1.15
Platform: Macintel
Screen: 834x1194
Window: 1194x704
DevicePixelRatio: 2
DeviceOrientation: landscape-primant

iOS:

User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS
X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4
Mobile/15E148 Safari/604.1
Platform: iPhone Screen: 393x852
Window: 393X741
DevicePixelRatio: 3
DeviceOrientation: portrait-primary.

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Tablet (iPad, Galaxy Tab o.ä.)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by techotline** [comment]
Es tatsächlich ein generelles Problem. Passiert aktuell auf allen Gerätetypen.

**Comment by ptitmouton** [comment]
Hier liegt kein Fehler vor, durch den Hotfix war der Prod-Stand nur auch auf Staging gelandet.
