### ISSUE TITLE
Admin-Content hat kein Padding

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#173]
### Bug-Beschreibung

Problem tritt bei allen Gerätetypen auf.

Produktivsystem:

<img width="981" alt="buttons-ps" src="https://github.com/lotta-schule/web/assets/153733311/cebffd11-b90b-451a-bc49-45a737c3a203">

<img width="1250" alt="cockpit-ps" src="https://github.com/lotta-schule/web/assets/153733311/e16d23e6-3bcf-4eed-ad0a-113505aa7aac">

Testumgebung:

<img width="1251" alt="kategorien-test" src="https://github.com/lotta-schule/web/assets/153733311/ebccd735-5a14-43a7-ad7e-6237ffb8c853">
<img width="1248" alt="cockpit" src="https://github.com/lotta-schule/web/assets/153733311/3996573a-aeaf-493e-abeb-753cf5855c9e">
<img width="1250" alt="admin-darstellung" src="https://github.com/lotta-schule/web/assets/153733311/4fc23da9-4765-4aec-99b5-25c26b30250b">
<img width="1255" alt="buttons" src="https://github.com/lotta-schule/web/assets/153733311/1b946eda-0b6c-4784-9aba-0d238b5f57b7">
<img width="1440" alt="cockpit-fullscreen-test" src="https://github.com/lotta-schule/web/assets/153733311/93f704da-03c7-413e-b094-fd3808f7ef71">

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Ja das ist bekannt und vorübergehend so gewollt

**Comment by techotline** [comment]
@ptitmouton I.O.

**Comment by techotline** [comment]
@ptitmouton I.O. 
Ich bin davon ausgegangen. Du weist jedoch, was ich meine. 👍🏻
