### ISSUE TITLE
[Bug]: Fehlerhaftes padding für content view in Nachrichten (nur Staging)

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#177]
### Bug-Beschreibung

padding-inline: var(--lotta-spacing) ist ggf. Problem

Desktop:
<img width="1440" alt="messaging" src="https://github.com/lotta-schule/web/assets/153733311/484850ab-af36-4f11-b8ca-adf5f1d15550">

Mobil:
![m1](https://github.com/lotta-schule/web/assets/153733311/6f040824-44f1-4c08-b0fd-aad816c90504)
![m2](https://github.com/lotta-schule/web/assets/153733311/90bc3a69-b7d4-49c4-a1b2-f860aa5194bb)
![m3](https://github.com/lotta-schule/web/assets/153733311/830cc355-9067-4442-b58b-4ed62037b143)

### Link zur Seite, auf der das Problem aufgefallen ist

.staging

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@BillyTheKing Ich finde es ziemlich nervig dass sich die Seitenleiste der Nachrichtenansicht (aufgrund des transparenten Hintergrund ist hier Padding auf die ListItems gesetzt) so anders Verhält als woanders auf der Seite. Eventuell können wir da mal bei Gelegenheit drüber reden.
Allgemein würde sich unser Layout v.A. auf Seiten ohne Seitenleiste denke ich um einiges Verbessern können, wäre Aufwand aber wir könnten die Gelegenheit mal nutzen unser Layout mal systematisch anzugehen. 
Werde das bei unserem nächsten Treffen nochmal ansprechen.
