### ISSUE TITLE
[Bug]: Input inline in Nachrichten "springt" bei Eingabe

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#178]
### Bug-Beschreibung

Möchte man eine neue Nachricht verfassen, dann wird diese "Anfrage" nicht sauber verarbeitet. Es tritt ein "springen" auf, wenn ein Wort formuliert wird.

### Link zur Seite, auf der das Problem aufgefallen ist

general

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Das Problem haben wir schon ewig.

Wir müssen die Höhe des Textfeldes zurücksetzen damit wir wissen wie hoch es sein muss damit der Text reinpasst, dann ändern wir es zurück auf die nötige Größe. Das passiert bei jedem geänderten Buchstaben.
Hier ist einfach React zu langsam. Vielleicht habe ich eine einfache schnelle Lösung.
