### ISSUE TITLE
Mobil: Nutzermenü: Tableiste: Buttons sind etwas klein und haben wenig Padding

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#188]
### Bug-Beschreibung

Der Datenabstand links im body der Split View Komponente sowie oben im mobilen Nutzermenü ist zu gering und sollte angepasst werden, um den Content wieder übersichtlicher darzustellen. Z.B. Profilbild hat falsche Größe.

Produktivsystem:
![menu-user](https://github.com/lotta-schule/web/assets/153733311/c47b7653-6992-4245-9404-3eab87ed55f1)

Testumgebung:
![menu-user_1](https://github.com/lotta-schule/web/assets/153733311/f643563d-77cf-4e32-a899-6a23101eca7f)

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Ist das wirklich relevant? Für mich sieht es ok aus, man kann ja eh swipen.

Also ich werde mir nicht die ganze Woche die Nächte um die Ohren schlagen um so krümelkackige Pixel-Schubserei zu machen. Das ist Verschwendung von Expertise.

@BillyTheKing Bitte mal melden und Bescheid geben ob du es machst und wenn ja ob du es noch in den nächsten 5 Tagen machen möchtest und dann setz bitte Projekt / Labels / Zuweisung dementsprechend.
Ich habe in https://github.com/lotta-schule/web/pull/171/files das Profilbild kleiner gemacht (das vorher auch einfach zu groß war) und die Abstände irgendwie auf unsere einheitliche Größe gebracht. Ich kann und will die Pixel nicht schubsen, das ist deine Aufgabe.
