### ISSUE TITLE
(Mobil) Beitrag Bearbeiten: Text-Modul - Toolbar zur Formatierung bricht aus Container aus

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#189]
### Bug-Beschreibung

Ich denke, an dieser Stelle reicht ein Screenshot aus, um meine Fehlermeldung zu verdeutlichen.

![content-modul-bug](https://github.com/lotta-schule/web/assets/153733311/11b169b9-9c3f-4c36-a837-cf4e27562358)

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Das lasse ich nur halb als Regression gelten, das hat sich vermutlich nie anders verhalten seitdem wir diese Leiste haben ...

@BillyTheKing Die Buttons sind ganz leicht größer geworden (https://github.com/lotta-schule/web/pull/182/files), ich habe hier von unerklärlichen Dezimal-em-Einheiten auf var(--lotta-spacing) umgestellt (Ich brauchte auch eine einheitliche bekannte Größe um Icon+CircularProgressBar auf dem LoadingButton mittig setzen zu können. Sonst sieht das bei der nächstgrößeren Schriftart ja auch alles schief aus). 
Das ist nun anscheinend genau die Größe ab der das auf etwa iPhone-Bildschirmen einen Overflow gibt, ich gehe davon aus kleinere Geräte haben das schon länger so gesehen 😅

Scrollen oder umbrechen?

**Comment by techotline** [comment]
@ptitmouton Ich wäre für umbrechen. Somit wird auch das Tool anwenderfreundlich.
