### ISSUE TITLE
[Feature]: Beiträge werden mit Link sichtbar, wenn zugehörige Kategorie gelöscht wird

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#193]
### Bereich

Administrationsbereich (inkl. "Feedback")

### Verhalten

Verhalten

### Problem

Ist ein Beitrag einer Kategorie angehängt und wird diese Kategorie anschließend gelöscht, sind diese Beiträge nur noch über einen direkten Link zu erreichen. Der Administrator, der diesen Vorgang bearbeitet, wird mithilfe eines Dialogs über die Folgen informiert.

<img width="1423" alt="Kategorien-löschen" src="https://github.com/lotta-schule/web/assets/153733311/77b60a01-8c27-4243-ab62-12a61cd3b385">

Sollte also eine Kategorie, der bspw. 100 Beiträge zugeordnet sind, aus diversen Gründen unwiederbringlich gelöscht werden, müsste ein Administrator alle Beiträge verändern, um sie ordnungsgemäß für Nutzer anzuzeigen. Dieser Prozess ist mit beträchtlichen Aufwand verbunden.

### Beschreibung

**Lösung**
Nach dem Löschen einer Kategorie sollten alle Beiträge, welche nur sichtbar für jene Kategorie waren, automatisiert in den Status "zur Kontrolle freigeben" zurückversetzt werden. Die Autoren der entsprechenden Beiträge sollten man zudem über den Vorgang benachrichtigen. #35 ist ein guter Vergleich, um die gewonnene Expertise auch an dieser Stelle umzusetzen.

**Comment by BillyTheKing** [comment]
Wir durch Ticket #96 abgedeckt.
