### ISSUE TITLE
(mobil) Drawer wird abgeschnitten, sobald User zusätzlich einen Beitrag geöffnet hat

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#195]
Staging: Öffnet man das mobile Nutzermenü auf dem iPhone, dann wird dieses ein wenig angeschnitten, wenn vorher ein Beitrag angeklickt wurde, in dem der User sich befindet.

![bug-drawer-25-03-2024](https://github.com/lotta-schule/web/assets/153733311/d259cad3-8085-4086-87e3-0620d44a9641)

Browser: Safari

**Comment by ptitmouton** [comment]
Ist das Problem nicht durch #127 gelöst?

Bitte mehr Informationen über die Umstände, in denen das Porblem auftaucht.

Gerät, Link, etc ...

**Comment by ptitmouton** [comment]
Body scroll nicht, und Marginale scrollt auch nicht mit dem Body mit.

Problem ist das iOS eine falsche Höhe meldet wenn die Safari-Toolbar unten eingeklappt ist.

**Comment by ptitmouton** [comment]
Duplikat #127
