### ISSUE TITLE
[Bug]: presentation: border radius für Tags hat einen falschen value und wird nicht übernommen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#196]
### Bug-Beschreibung

Der border-radius wird derzeit zuverlässig für Rundungen in der Navigation sowie für Buttons übernommen. Für Tags, die ebenfalls eine Umrandung haben, werden diese Maße nicht ordnungsgemäß definiert. D.h., Tags akzeptieren ihre eigenen "Maße", anstatt sie aus dem Backend zu übernehmen.

<img width="527" alt="bug-bora-Tags" src="https://github.com/lotta-schule/web/assets/153733311/2b42279e-073b-43ac-bef7-2140cc33aaab">

<img width="524" alt="bug-bora-Tags_2" src="https://github.com/lotta-schule/web/assets/153733311/f03eda50-69ed-4d47-81fc-31b831d4fdcf">

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
@techotline Bitte Fehler kurz beschreiben, Danke.
