### ISSUE TITLE
[Feature]: Dateiverwaltung: Teilbare Ordner für Nutzer integrieren

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#197]
### Bereich

Datei- und Medienverwaltung

### Verhalten

Verhalten

### Grundidee

Teilbare Ordner soll es Usern zukünftig ermöglichen, Dateien und Dokumente effizient mit anderen Personen zu teilen, an diesen zusammenzuarbeiten und sich untereinander zu organisieren.

**UI:**

- Die Benutzeroberfläche sollte benutzerfreundlich und intuitiv sein.
- Das Cockpit, in dem User ihre geteilten Ordner verwalten, neue Ordner erstellen und bestehende bearbeiten können.
- Ein klarer Mechanismus zum Hinzufügen von Usern zu einem geteilten Ordner und zum Festlegen von Berechtigungen.

**Ordnerstruktur:**

- Ein hierarchisches Ordnungssystem, das es Nutzern erlaubt, _Ordner und Unterordner_ zu erstellen und zu organisieren und diesen _andere Nutzer zuzuweisen._ 
- Ggf. Tags oder Labels zur einfachen Kategorisierung und Suche von Inhalten.

**Teilbarkeit und Zugriffssteuerung:**
Die Möglichkeit, einen Ordner oder eine Datei mit anderen Benutzern zu teilen, müsste von den eingeladenen Nutzern bestätigt werden. Verschiedene Zugriffsstufen, z. B. Lesezugriff, Schreibzugriff oder Administratorzugriff, um die Kontrolle über die gemeinsam genutzten Inhalte zu behalten. Derjenige, welcher den Ordner erstellt, darf diese Rechte vergeben. Optionen zur zeitlichen Begrenzung von Freigaben oder zum Widerrufen von Zugriffsberechtigungen.

**Kollaborationstools:**
Eingebaute Kollaborationstools wie **Kommentare, Markierungen oder Notizen**, um die Zusammenarbeit innerhalb des geteilten Ordners zu erleichtern. Echtzeitaktualisierungen, um sicherzustellen, dass alle Benutzer die neueste Version einer Datei oder eines Dokuments sehen.

**Aktivitäten überwachen:**
Optionen zur Überprüfung von Benutzeraktivitäten und zum Nachverfolgen von Änderungen innerhalb des geteilten Ordners.

### Beschreibung

Ein Struktur, welche skalierbar ist und mit dem Wachstum der Benutzerbasis problemlos umgehen kann.
Verfügbarkeit auf verschiedenen Plattformen wie Web, Desktop und mobilen Geräten, um die Zugänglichkeit zu gewährleisten (Responsivität).

**Comment by ptitmouton** [comment]
Ich sag's wie es ist dieses Ticket ist *deutlich* zu umfangreich und detailliert und lässt auch so wenig Spielraum für Diskussion, dass ich es nicht für nutzbar halte. Die Möglichkeit, Dateien auszutauschen wird kommen, aber das werden wir behutsam und wohldurchdacht angehen, überlegen wie wir den Nutzern das, was sie damit erreichen wollen Stück für Stück näher bringen können ohne uns dafür ein halbes Jahr im Keller einsperren zu müssen um dann ein kompliziertes schwer wartbares Monstrum hervorzubringen dass lauter Datenleichen hinterlässt und vielleicht am Ende gar keiner so nutzen möchte.

Wenn wir nicht aufpassen bauen wir hier nur [schnellere Pferde](https://www.noahleidinger.com/ideenraum/schnelle-pferde-funktionen)

Das Ticket lasse ich trotzdem erstmal zur Orientierung offen, bis wir zumindest einen sinnvollen Weg haben, wie wir das ganze anpacken wollen, und es durch (viele) andere ersetzen können.

**Comment by ptitmouton** [comment]
Da dieses Ticket weiter referenziert wurde, denke ich es wäre zugunsten klarer Kommunikation besser gewesen das Ticket gleich zu schließen. Ich hatte mich anscheinend gestern etwas unklar hierzu ausgedrückt. 

Das Ticket ist zu umfangreich, erklärt überhaupt nicht **warum**, bietet keinen Spielraum, keine Optionen und schließt uns, unsere Zeit, technische Möglichkeiten und Zweck des Umzusetzenden aus der Diskussion aus. Es ist in dieser Form unbrauchbar und ich schließe es.

Wir denken über eine Lösung nach die wir in überschaubarer Zeit realisieren können und die als Startpunkt dienen kann, ausgebaut zu werden wenn wir sie unseren Nutzern gegenüber validiert haben.

Wenn wir Pläne in diese Richtung konkretisiert haben wirst du sicher davon erfahren und auch Feedback geben können.
