### ISSUE TITLE
UI Admin: Kategorien und Marginalen: Buttons haben wenig Margin 

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#209]
### Bug-Beschreibung

Im UI für Kategorien oder Marginalen haben die Buttons wenig Margin zum unteren Rand!

Mobil:
![pad-kat-buttons](https://github.com/lotta-schule/web/assets/153733311/9cfba511-11ae-471a-a2f2-084ecabd213a)

Desktop:
<img width="996" alt="desktop_kat-padding-buttons" src="https://github.com/lotta-schule/web/assets/153733311/3886fff5-497a-468e-9efa-cd832e361d2a">
<img width="1249" alt="padding-marginalen-buutons" src="https://github.com/lotta-schule/web/assets/153733311/7a3ed354-75c5-4243-b886-92c196759322">

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@techotline ich habe ein Label 'Staging' erstellt, das kannst du gerne nutzen für Probleme die du ausschließlich auf Staging vorfindest. Finde das für die Übersichtlichkeit und die angestrebte Langlebigkeit der Titel als Label etwas besser aufgehoben als im Titel. 

Im Moment können wir ja aber eh die seltenen Tage genießen an denen genau dieselbe Version auf beiden deployt ist ;)

**Comment by BillyTheKing** [comment]
@techotline die Positionierung ist jetzt bewusst so

**Comment by wie0815** [comment]
@BillyTheKing Schließe mich @techotline an. Das gibt Ärger, wenn nach Jahren die Buttons die Positionierung wechseln. Das führt zum Löschen von Beiträgen, da man gelernt hat, unten rechts auf Speichern zu klicken. LG

**Comment by BillyTheKing** [comment]
Ursprüngliche Positionierung der Buttons wiederhergestellt. Siehe https://*.preview-237.lotta.schule (https://info.preview-237.lotta.schule/admin/categories/list)
