### ISSUE TITLE
[staging]: /widgets + /categories: Seite lässt sich horizontal in Leere scrollen, weil Teile der Split View abgetrennt werden (mobil)

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#210]
### Bug-Beschreibung

Öffnet man das UI für Marginalen auf dem iPhone, dann werden Teile der Split View mit einen falschen value angezeigt, womit die Seite sich horizontal scrollen lässt.

![staging_marginalen](https://github.com/lotta-schule/web/assets/153733311/9094c5d9-3c67-48b1-982f-3d7927e394d7)
![staging_kategorien](https://github.com/lotta-schule/web/assets/153733311/a77f7af5-672a-42cf-8ae4-ca6f7e181efc)

### Link zur Seite, auf der das Problem aufgefallen ist

staging

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Werde das mal für einen ersten (und hoffentlich einzigen) Hotfix übernehmen @BillyTheKing 
Bin mir nicht sicher ob 'Bug' nicht etwas viel der Ehre ist, aber es ist wahrscheinlich blöd genug dass wir das nicht die nächsten 5 Monate haben wollen und je näher Prod und Dev sind desto weniger Abfuck ist es auch. 

Werds mir mal ansehen, aber vermutlich erst nach Ostern.

**Comment by ptitmouton** [comment]
Habe es auf production gefixt.

https://github.com/lotta-schule/web/commit/3e5085300d0758f93c38fc02096b63c152c7dbf1
