### ISSUE TITLE
CircularProgress anpassen

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#211]
### Bug-Beschreibung

Lädt man eine Datei in seinen Medienspeicher (> "Meine Dateien und Medien") z.B. in einen seiner beliebigen Ordner hoch, erscheint beim Upload grundsätzlich ein Loading Circle (CircularProgress), der den Status des aktuellen Vorgangs in Prozent visuell darstellt.

<img width="1440" alt="upload-file_1" src="https://github.com/lotta-schule/web/assets/153733311/22da9ac7-0d49-48e5-9a3c-10d570a33dd2">

![mobil_cp-1](https://github.com/lotta-schule/web/assets/153733311/521f8284-39c0-4e33-b52d-a3fb3d4d9cef)

Storybook:

<img width="1211" alt="CircularProgress-storybook" src="https://github.com/lotta-schule/web/assets/153733311/a2769f96-f232-4fd4-a710-82978acc3301">

### Gerätekategorie

iOS / MacOS / iPadOS

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@BillyTheKing Wie sieht's hiermit aus?

Bei mir sieht das zwar nicht ganz so schlimm aus aber ganz sauber sieht hier die 100 nicht aus. Du hast keine weiteren Angaben gemacht @techotline  ist das alles iOS?

Normalerweise ist das grundsätzlich mehr oder weniger quatsch "100%" anzuzeigen, im Normalfall wollen wir ja eher dazu übergehen stattdesen eine Erfolgsmeldung / Ein Haken o.ä. zu zeigen.
Ich denke wenn wir `fontSize` etwas runterstellen und `textLength` rausnehmen, was nämlich dazu führt dass die Charakterabstände plötzlich von riesig bei 99 auf winzig bei 100 springen dann sollte das passen.

`fontAdjust` klingt ehrlich gesagt eh nach einer dummen Idee. Scheine ich damals verbrochen zu haben
https://github.com/lotta-schule/web/commit/8bed6cd04dbcd99d1f798cb544670bb416472288#diff-24aefb41c3d81d1605e112f69a841df79c55217de4ff2949eb742b5bd2c85123
