### ISSUE TITLE
Medienbrowser schöner machen

### ISSUE THREAD

**Issue by ptitmouton** [lotta-schule/web#213]
@BillyTheKing hat sich schon vor längerer Zeit einen schöneren Browser für Dateien überlegt.

Der müsste jetzt auch mal fertig implementiert werden.

**Comment by ptitmouton** [comment]
Auf folgendes bin ich gestoßen sollten wir noch besprechen:

(Ich erwarte keine AW, ist eine Erinnerungsstütze. Können wir Mi drüber reden)

- Vorschau
- Icons
- Uploads
- mobil (Multiview? + Toolbar + Seitenleiste)
- Aktionsdialoge & DirectorySelector
- SelectFile-Button/Overlay Auswahldialog
- Information zu Dateien verm klar aber was macht Seitenleiste bei Ordnern?

**Comment by ptitmouton** [comment]
- Upload wie gehabt, aber Häkchen nach erfolgreichem Upload
- @BillyTheKing macht FileIcons
- @BillyTheKing  überlegt sich was für öffentliche Ordner (in Zukunft geteilt)
- Auf Desktop verschwindet das Menü, stattdessen Rechtsklick
- Auf Mobil verschwindet das Menü, stattdessen Buttons in der Vorschauleiste

**Comment by BillyTheKing** [comment]
Webansicht:
![Image](https://github.com/lotta-schule/web/assets/11082197/4b27c31d-cb5d-4939-a34d-8bed6d99f6da)
![Image](https://github.com/lotta-schule/web/assets/11082197/e9f48311-6b2c-4e3d-a9e0-6045b2084d10)

Mobilansicht:
Ebene 1
![Image](https://github.com/lotta-schule/web/assets/11082197/a5540548-d6d7-4a64-8ef1-46546d20a812)

Ebene 1 - Klick auf Icon (3 Punkte) > Einstellungen für Ordner
![Image](https://github.com/lotta-schule/web/assets/11082197/3e96001e-fdbc-4765-a537-4dbe1d2a3360)

Ebene 2 - innerhalb eines Ordners, Auflistung von Dateien und Unterordnern
![Image](https://github.com/lotta-schule/web/assets/11082197/4f16a74a-d44f-4d20-99a1-1ff2d1097377)

Ebene X - Datei Vorschau, Infos und Bearbeiten
![Image](https://github.com/lotta-schule/web/assets/11082197/9a70d389-8786-4669-9a20-a3c29d7ca10f)

**Comment by ptitmouton** [comment]
Ich seh gerade dass du noch eine nichtlineare Historie eingebaut hast @BillyTheKing . Das wir ein Folgeticket werden müssen, ich will auch mal fertig werden...
Genauso die Suche. Das braucht eh noch Backendunterstützung und Mockups fehlen auch dazu. Das ist out of scope und wird später kommen müssen.

**Comment by ptitmouton** [comment]
> Ich vermisse eine Mehrfachauswahl für Dateien, die man anklicken kann, um sie als A) entweder downloaden zu können oder B) in einen neuen Ordner zu verschieben. Das ist in der Verwaltung wahnsinnig nervig, weil jede einzelne File auch separat über Dropdown verschoben werden muss. @ptitmouton Findest Du meinen Vorschlag sinnvoll, möchtest Du es mit dem aktuellen Dev umsetzen oder bedarf es eines zusätzlichen Tickets?
> 
> Sozusagen Checkbox oder "Dateien auswählen" wie für Module (z.B. Galerie -> Image hinzufügen)
> 
> <img alt="Bildschirmfoto 2024-04-26 um 16 39 17" width="700" src="https://private-user-images.githubusercontent.com/153733311/326015973-32e3f7ec-a5c0-43a0-96d9-a6dde863b7ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDQwNzYsIm5iZiI6MTcxNDE0Mzc3NiwicGF0aCI6Ii8xNTM3MzMzMTEvMzI2MDE1OTczLTMyZTNmN2VjLWE1YzAtNDNhMC05NmQ5LWE2ZGRlODYzYjdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxNTAyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjAxYTY3YjY5Y2QxYjE0OGM5ZWIwZTFlZGM5ZTVhYzkwYWE4MDAzZWMwNjc0NDk2NjhhNDQ2NDZiMTEwMjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ONP95FcWi1E_lfrqgkQlsmQyDwLlqxbarDYcRB_s2rM">
> Des Weiteren sollte die Anzahl der Dateien, die in einem Ordner liegen, übernommen werden.
> 
> <img alt="Bildschirmfoto 2024-04-26 um 16 33 48" width="600" src="https://private-user-images.githubusercontent.com/153733311/326014293-6201d7ee-d015-44d3-95ec-962f7f817a52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDQwNzYsIm5iZiI6MTcxNDE0Mzc3NiwicGF0aCI6Ii8xNTM3MzMzMTEvMzI2MDE0MjkzLTYyMDFkN2VlLWQwMTUtNDRkMy05NWVjLTk2MmY3ZjgxN2E1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxNTAyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWYzZDY3ODM5NmMyZjFjYjBkZDNkMGZiZGY1MjA5OWIyYjczMzRlZTgxMjg2OTg0MWVkYjgzMDEzN2EwNzIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K2OhbCcqCN7C0qSacSGqt9hjT8wseCqZwzIIyxzM2Ns">

Bin mir nicht sicher was du genau sagen willst. Falls du meinst das nach aktuellem Stand noch Sachen fehlen, das ist normal, das Feature ist ja auch noch lange nicht fertig …
Ich arbeite dran. 

Es wird alles gehen was momentan auch geht, also auch das markieren von mehreren Dateien mit Shift oder Cmd/Ctrl.

Checkboxen halte ich für keine gute Lösung, denn der hauptsächliche Zweck des Ansichtsmodus ist es nicht, eine Mehrfachauswahl zu treffen, und für alle anderen Use-Cases empfinde ich sie als störend und ablenkend. Ich denke das aktuelle Design von @BillyTheKing ist gut, wir haben viel darüber nachgedacht und diskutiert um zu der aktuellen Lösung zu kommen.

Für neue Features wie dem gleichzeitigen Download mehrerer Dateien bitte Ticket aufmachen. Gerade Multi-Download ist kompliziert, da nicht standardisiert

**Comment by ptitmouton** [comment]
@wie0815 @BillyTheKing ich habe bei dem neuen Medienbrowser so langsam einem Stand erreicht den ich gerne vorsichtig als fast vollständig betiteln würde.


## Kurze (oder nicht) Zusammenfassung
 
Ist vom Aufwand **deutlich** umfangreicher geworden als ich es vorhergesehen hatte, letzten Endes ist es in großen Teilen eine Neuimplementierung, wenn man von den Dialogen (Neuer Ordner, Ordner löschen, Datei löschen, Dateien und Ordner verschieben) absieht, wobei es auch hier Änderungen gab.

Im Großen und Ganzen denke ich dass uns durch das Mockup von @BillyTheKing hier eine deutlich modernere als auch übersichtliche Dateiauswahl gelungen ist, die den Dateien selbst mehr Raum gibt als vorher. 

### Desktop-Nutzung

Am auffälligsten ist das Update wohl für Desktop-Nutzer, dort sind nun mehrere Verzeichnis-Ebenen gleichzeitig sichtbar.
Auf der rechten Seite ist nun dauerhaft ein InfoPanel sichtbar, das neben Informationen und Vorschau (beides bei Mehrfachauswahl eingeschränkt) auch mögliche Aktionen über Buttons für die aktuelle Auswahl bietet. 
Dieselben — verfügbaren — Aktionen können alternativ durch Rechtsklick auf einen Eintrag (oder auch auf eine Sammlung von Einträgen) über das Kontextmenü ausgelöst werden.

*Die Drei-Punkte-Menüs in jeder Zeile haben wir damit auf großen Bildschirmen abgeschafft.*

Die Auswahl von mehreren Knoten für fortgeschrittene Nutzer soll auch weiterhin wie gehabt über die Tastatur erfolgen. Shift für von-bis und Cmd(Ctrl für Linux-Nutzer oder auch diese vom Leben geschundenen Windows-infizierten) um einzelne Knoten zur Auswahl hinzuzufügen. Mit Cmd+A lässt sich der ganze aktuelle Inhalt auswählen. 

Das Auswählen mehrerer Knoten aus verschiedenen Pfad-Ebenen geht nicht! Das hat Probleme hervorgerufen über die ich erstmal nicht nachdenken wollte.

### Kleine Bildschirme (verm Telefone)

Auf Geräten mit kleinen Bildschirmen haben wir uns entschieden die Möglichkeiten zu begrenzen. Hier ist die Bedienung deutlich näher an bisherigen Vorgehensweise, nur mit aktualisiertem Unterbau: Es ist jeweils nur der Inhalt eines einzelnen Ordners gleichzeitig zu sehen, Ordner haben die bekannten Drei-Punkte-Menüs.

*Eine Mehrfachauswahl ist mobil (im Standardmodus) nicht vorgesehen.*

Durch Tippen auf eine Datei wird das InfoPanel geöffnet, um weitere Informationen zur Datei einzusehen oder Aktionen auszuführen. Das InfoPanel ist hier das gleiche. Über den Zurückpfeil lässt sich das Panel schließen. 

### Dateien und Ordner anlegen 

Die Buttons zum Erstellen eines neuen Ordners und zum Hochladen einer Datei sind bei entsprechender Berechtigung weiterhin oben rechts in der Leiste zu finden. Auf allen Geräten und in allen Modi.

Der Upload ist grundsätzlich sehr ähnlich geblieben, bietet ein wenig mehr Informationen. Ein Schließen des Browsers ist während des Uploads nicht mehr möglich! (Dazu gibt es schon das Folgeticket #227)

### Auswahl / Mehrfachauswahl

Ganz kurz zu den beiden anderen Modi:
Im Auswahl- und Mehrfachauswahl-Modus sind alle Aktionen (außer wie erwähnt Neuer Ordner+Upload) deaktiviert. Das war auch schon vorher so. Hier soll nur eine Auswahl getroffen werden.

*Für Geräte mit kleinen Bildschirmen ist das InfoPanel an der Seite nicht vorgesehen*

### Der Filter

Wie schon erwähnt gibt es den Filter vorerst nicht mehr. Er wird durch eine Suche ersetzt, vermutlich in 5.0. Ticket ist da, #228, Mockups von @BillyTheKing fehlen noch. 

## Was jetzt?

Auf technischer Seite ist bis auf einige Testdateien, die ich noch schreiben will, alles soweit vorbereitet. Der Branch ist aktuell auf https://(kürzel).preview-214.lotta.schule deployed. Preview-Umgebungen sind eine Kopie von Staging, mit jeweils eigener Datenbank. Nur die Dateien habe ich nicht von Staging angekoppelt - daran hatte ich nicht gedacht - . Grundsätzlich sollte das für euch aber eher ein Detail sein, auf Staging solltet ihr eh keine wichtigen Sachen hochladen (wird ja nach 1 Woche eh gelöscht). Wie bei Staging könnt ihr Dateien auf Preview löschen, die ihr auf prod hochgeladen habt, ohne prod zu beeinträchtigen. Die Datei wird dann nicht wirklich gelöscht. Nur Achtung, Emails werden echte rausgeschickt!

Würde mich freuen wenn ihr euch (mit Unterstützung von @techotline ) mit dem oben zusammengefassten Wissen mal auf die Suche nach Problemen machen könntet. Interessant ist für mich alles was nicht läuft aber so wirkt als sollte es laufen, was eventuell einen inkonsistenten Zustand hervorruft, oder (bis auf bekannte Ausnahmen) vorher ging und nun nicht mehr. 

Am Besten dann einfach hier im Ticket sammeln, möglichst knapp und verständlich, und vielleicht auch nicht unbedingt 10 kleine Fehler in einzelnen Kommentaren. Da klingelt wieder nur die Mailbox.

Bin dann erstmal im Urlaub, werde mich in der nächsten Woche eher schlecht erreichbar.

**Comment by ptitmouton** [comment]
Ah ja, guter Einwand, habe ich vergessen zu erwähnen:

Hatte mit @BillyTheKing erstmal abgesprochen, die Möglichkeit auszulassen, neue öffentliche Ordner zu erstellen. Öffentliche Ordner sind etwas verwirrend und von vornherein auch eine Notlösung gewesen (es sind technisch gesehen einfach Ordner ohne Nutzer).

Diese Entscheidung war gefallen, als wir noch davon ausgegangen waren dass es für 5.0 zumindest irgendeine Art von Roadmap für eine Alternative geben würde. 

Ich persönlich lasse würde mich vermutlich von @wie0815 überzeugen lassen, dass wir unbedingt öffentliche Ordner erstellen können müssen, da wir aber jedem neuen Lotta einen öffentlichen Ordner beilegen, und wir eigentlich eher früh als spät eine Alternative zur Verfügung stellen möchten, würde ich ehrlich gesagt vorerst bei der Entscheidung bleiben.

Was die Kennzeichnung angeht, so ist sie in der Seitenleiste bei den anderen Infos (erstellt am) zu finden. Ich stimme zu dass das etwas unauffällig ist, wir hatten eigentlich auch ausgemacht dass es wieder ein Extra-Icon gibt, das ist in Eifer des Gefechts dann wieder untergegangen. 
@BillyTheKing Machst du bei Gelegenheit noch ein Icon?

@wie0815 Feedback zum Browser im Allgemeinen und zur Öffentlicher-Ordner-Frage im Speziellen gern gesehen.

**Comment by ptitmouton** [comment]
@BillyTheKing @techotline @wie0815
Wie sieht es hier aus? Ist noch niemand dazu gekommen oder habt ihr tatsächlich keine Probleme gefunden?

**Comment by ptitmouton** [comment]
> 2. Neu erstellte, leere Unterordner werden bei mir nicht angezeigt, **sobald** ich eine Datei ausgewählt habe, um jene Datei in diese zu verschieben.
> [...]
> -> der Ordner "**TEST**" ist anscheinend "nur" imaginär vorhanden und wird, wenn er leer ist, nicht gefunden. Ordner in Ordner ist möglich, nur das Ändern des Pfades einer Datei nicht.

Verstehe ich nicht oder kann ich nicht nachstellen.
Kannst du bitte die Schritte wiedergeben die notwendig sind, um das Problem zu verursachen?

Screenshots können manchmal hilfreich sein aber in der Regel ist eine gut geschriebene Beschreibung deutlich hilfreicher, vor Allem wenn der Fehler darin besteht, dass man *nichts* sieht ..

**Comment by wie0815** [comment]
@ptitmouton Habe das gleiche Problem und versuche es zu beschreiben. Wenn in einem Ordner **A** Dateien liegen (z.B. Bilder) und man erstellt in diesem Ordner einen Unterordner **B**, ist es nicht möglich eine Datei in den neu erstellten Unterordner zu verschieben. Ordner, die auf der gleichen Ebene wie die Datei liegen, werden im aufpoppenden Fenster nicht angezeigt.

Bsp. vgl. Bildschirmfoto:
1. Im Ordner "Bilder klein" liegen 5 Bilder
2. Der Ordner "Test" wurde neu erstellt.
3. Möchte mann das Bild "Dreh1.jpg" in den Ordner "Test" verschieben, ist das nicht möglich, da im aufpoppenden Fenster nur die Ordner der übergeordneten Ebene angezeigt werden, also "Bilder gross", "Galerien", "PDF" usw.

<img width="1275" alt="Bildschirmfoto 2024-05-22 um 18 38 36" src="https://github.com/lotta-schule/web/assets/143288974/b0c400c3-ba6e-47eb-8443-54c7dd3e2b5f">

**Comment by ptitmouton** [comment]
@wie0815 Ok dann habe ich das jetzt verstanden.

Das ist so gewollt damit man einen Ordner nicht in sich selbst verschiebt. Für Dateien sollte das natürlich nicht gelten.
