### ISSUE TITLE
MockUps für Reaktion-Funktion

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#216]
Reaktion für Beiträge:

- [x] Auswahl an Icons
- [x] Ansicht für User/Autoren &  public (Button ausgegraut)
- [x] Einstellung für Article-Edit

Die Umsetzung wird in #130 geplant

**Comment by BillyTheKing** [comment]
![Reaktions Funktion – Beitrag Bearbeiten@2x](https://github.com/lotta-schule/web/assets/11082197/3e381478-67b8-4eda-9ab0-483a998ca96b)
![Reaktions Funktion@2x](https://github.com/lotta-schule/web/assets/11082197/c4dfbdec-eff1-4cef-ae81-8fcedf53f2fd)

**Comment by ptitmouton** [comment]
@BillyTheKing Ich vermute die lila Striche sollen heißen es erscheint bei Klick / Tap?

Mir wäre angesichts der Probleme die die Positionierung von Tooltips gerade Cross-Platform immer machen eine Lösung ohne fast lieber gewesen ...

Woher sind die Icons?

**Comment by BillyTheKing** [comment]
Korrekt, die lila Striche zeigen lediglich die Zugehörigkeit der Tooltips. Die Positionierung ist letztendlich dieselbe, nämlich direkt über dem angeklickten Symbol/Button.

Ich kann mir gern Gedanken über eine Lösung ohne Tooltips machen. Meine ersten Ideen dazu sind **wahrscheinlich** mit einem höheren Styling Aufwand, durch die Responsivität verbunden, was nicht heißen soll, dass ich keine Lösung finde ;)

Die Icons sind alle von FA.

**Comment by ptitmouton** [comment]
✅ Alles notwendige erledigt
