### ISSUE TITLE
[Bug]: Dialoge lassen sich nicht scrollen, wenn sie zu lang werden

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#217]
### Bug-Beschreibung

Dialoge lassen sich nicht Scrollen, wenn ihr Inhalt zu lang ist.

Das betrifft nur größere Bildschirme, •nicht• mobile Ansichten.

Beispiel:

Befindet man sich in dem Dialog der Tooltips für Avatare und Tags und es möchte in diesem Dialog gescrollt werden, um anschließend alle aufgelisteten Beiträge einzusehen, welche aufgrund der beschränkten Bildschirmgröße verdeckt sind, ist dieser Vorgang momentan nicht möglich.

<img width="1440" alt="2024-04-10-B" src="https://github.com/lotta-schule/web/assets/153733311/2ea316d3-85fe-4621-a891-a321d7fbf02b">

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/

### Gerätekategorie

> mobil (Getestet auf 700x400)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Durch Hotfix direkt in prod gelöst

(Siehe 6c6d9f4e339aa0d5a25f89c09a060206c11205f4)
