### ISSUE TITLE
Nachrichten: Beim erstellen einer neuen Konversation schließt das SplitView die Navigation nicht, so dass keine Nachricht geschrieben werden kann

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#223]
### Bug-Beschreibung

Ein Nutzer hat gemeldet, dass er nach erfolgreicher Eingabe eines Nutzernamens vergeblich versucht hat, in die von ihm gewünschte Konversation zu gelangen. Stattdessen wurde er immer wieder auf die Nachrichtenseite (Übersicht aller Chats) zurückgewiesen. Der Chat öffnet sich nicht, der Vorgang wird an dem Punkt abgebrochen, in dem 'Nachricht verfassen' ausgewählt wurde. Der Befehl zum Verfassen einer neuen Nachricht wird demzufolge nicht ordnungsgemäß ausgeführt.

Informationen über sein System:

User-Agent: Mozilla/5.0 (Linux; Android 10; K)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/123.0.0.0 Mobile Safari/537.36
Platform: Linux armv81
Screen: 412x915
Window: 412x840
DevicePixelRatio: 2.625
DeviceOrientation: portrait-primary

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Chrome (Edge, Opera, ... )

**Comment by ptitmouton** [comment]
Ich kanns auf Chrome für Android auf meinem Testgerät hier nachstellen.
Ich kanns allerdings auch mit Webkit auf meinem iPhone nachstellen....

Wo wurde das noch getestet?

**Comment by ptitmouton** [comment]
Ja bitte in Zukunft präzise sein und nicht schreiben "nur Android" wenn es gar nicht der Fall ist.
Dann lieber nichts schreiben oder einfach schreiben dass man es nicht ausprobiert hat.

Das kommt jetzt wirklich alles andere als günstig

**Comment by ptitmouton** [comment]
> > Ja bitte in Zukunft präzise sein und nicht schreiben "nur Android" wenn es gar nicht der Fall ist.
> > Dann lieber nichts schreiben oder einfach schreiben dass man es nicht ausprobiert hat.
> > Das kommt jetzt wirklich alles andere als günstig
> 
> Es tut mir leid! Ehrlicherweise muss ich gerade selber an mir zweifeln ..., bin ich auch der Meinung, es getestet zu haben.

Sorry bin einfach etwas angefressen weil das ein paar Stunden Arbeit statt einer halben wird, wollte nicht dass du dich angegriffen fühlst.

Hätte ich vor zwei Wochen gewusst dass es alle mobilen Geräte betrifft und nicht einen einzelnen Android-User hätte ich vermutlich gleich ein Hotfix gemacht, was deutlich einfacher gewesen wäre als jetzt, da ich das komplette Dev-Setup und alle Pipelines aktualisiert habe.

Wie gesagt, bitte Mutmaßungen als solche kennzeichnen und vorsichtig mit Tatsachenaussagen sein.

**Comment by ptitmouton** [comment]
In Commit 8d9f95e1fc0a5ee18b44e7da5da3a00fed8fd55f gelöst, v4.2.7 ist als Hotfix raus.
