### ISSUE TITLE
Neue Schriftarten für Lotta

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#243]
Neue Schriftarten:

- https://fonts.google.com/specimen/Nunito
- https://fonts.google.com/specimen/Inter
- https://fonts.google.com/specimen/Teachers
- https://fonts.google.com/specimen/Assistant
- https://fonts.google.com/specimen/Ibarra+Real+Nova
- https://fonts.google.com/specimen/Cormorant?stroke=Serif

Neue Schriftarten **nur für Überschriften**: 
- https://fonts.google.com/specimen/Cormorant+SC?stroke=Serif
- https://fonts.google.com/specimen/Grandstander

_Originally posted by @BillyTheKing in https://github.com/lotta-schule/web/issues/97#issuecomment-2094809378_

**Comment by ptitmouton** [comment]
@techotline Warum machst du ein neues Ticket auf? Ist dir das andere nicht mehr gut genug? ;D

**Comment by ptitmouton** [comment]
Duplicate #97
