### ISSUE TITLE
react-beautiful-dnd ersetzen

### ISSUE THREAD

**Issue by ptitmouton** [lotta-schule/web#253]
Wir sollten unsere drag-n-drop library ersetzen.

[react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) wird seit einiger Zeit nicht mehr weiterentwickelt und macht immer mehr Probleme.
Mit dem Update zu React 19 scheint es quasi unbenutzbar geworden zu sein.

[pragmatic-drag-and-drop](https://github.com/atlassian/pragmatic-drag-and-drop) scheint der "sprituelle" Nachfolger zu sein.

**Comment by ptitmouton** [comment]
Erledigt in #262 

Das verschieben von Modulen in Beiträgen habe ich erstmal hinten fallen lassen. Es kam mir irgendwie extram unhandlich vor und ich frage mich ob wir das überhaupt brauchen.

Wenn sich keiner beschwert belasse ich es bei den Pfeilbuttons zum Hoch- und Runterschieben, und ich würde vorschlagen das schieben der Sachen fällt weg @BillyTheKing  @wie0815

**Comment by wie0815** [comment]
@ptitmouton Schieben finde ich schöner, doch sind Pfeile zum Klicken sind auch ok. Perspektivisch, wenn es eine schicke Möglichkeit gäbe, die irgendwann umgesetzt werden kann, wäre es prima, wenn wir es wieder ermöglichen.
