### ISSUE TITLE
Administrationsbereich: Gruppe bearbeiten: Absturz der Seite wenn Gruppe aufgerufen wird, die mehr als ein Einschreibeschlüssel hat

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#261]
### Bug-Beschreibung

- Einer bestehenden Gruppe wurde ein neuer Einschreibeschlüssel hinzugefügt.
- Anschließend wurde auf "Gruppe Speichern" geklickt.
- Folgende Fehlermeldung wurde sichtbar (siehe Bildschirmfoto!)
- Ein zweiter Versuch, die Gruppe zu bearbeiten scheiterte. Schon beim Auswählen der Gruppe wurde die gleiche Fehlermeldung ausgegeben (siehe Bildschirmfoto!)
<img width="1464" alt="Bildschirmfoto 2024-06-21 um 14 59 46" src="https://github.com/lotta-schule/web/assets/143288974/95104114-fdef-4ace-a5f9-4a08cf16b62f">

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/admin/users/groups

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by wie0815** [comment]
Danke für den Hinweis @techotline 

@ptitmouton Ich sehe hier ein Problem auf uns zukommen, da in den Sommerferien in der Regel alle Lottas "umgestellt" werden. 

Bei meinem beschriebenen Fall (siehe oben) sind alle Versuch gescheitert, im Admin-Bereich die Gruppe "Lehrer" zu bearbeiten, nachdem ich einen zweiten (neuen) Einschreibeschlüssel hinzugefügt habe. Auch nach dem erneuten Ab- und Anmelden und dem Löschen aller relevanten Daten blieb ich erfolglos. Die Fehlermeldung bleibt die gleiche. LG

**Comment by ptitmouton** [comment]
Problem besteht seit in #186, genauer gesagt  74e319174333b3bda680139bdd9e2eceb17ccba4 (deployed mit 4.2.0) eingeführt.

Einschreibeschlüssel werden alphabetisch sortiert um Vergleichbarkeit herzustellen und dadurch zu erkennen, ob die Gruppe bearbeitet wurde oder nicht (löschen eines Einschreibeschlüssels aktiviert "speichern" button, neu hinzufügen ans Ende der Liste deaktiviert ihn wieder)

Für die Sortierung wird [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) verwendet, aber falsch.

Hotfix mache ich fertig.

**Comment by ptitmouton** [comment]
Das Problem betrifft auch aktuellen Entwicklungsstand. Siehe #263
