### ISSUE TITLE
Marker für neue Beiträge wird nicht angezeigt

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#34]
Erstellt man einen neuen Beitrag und veröffentlicht diesen für alle oder für eine bestimmte Gruppe, wird dieser zwar auf der Startseite gesammelt, jedoch nicht mehr als neu mit einem Punkt markiert.

**Bug nachstellen:**
- angemeldet sein, vorzugsweise als Admin
- neuen Beitrag erstellen, an Kategorie anhängen und für alle sichtbar veröffentlichen
- Startseite aufrufen und neu laden
- Beitragsvorschau wird angezeigt, aber ohne Marker
(getestet auf info.lotta.schule)

**Mögliche Ursache:**
- unklar, finde über die Konsole keine relevanten Infos
- Idee: es könnte mit der Neugestaltung der article-previews zusammenhängen, ich kann mich nicht erinnern den Punkt berücksichtigt zu haben

**Comment by ptitmouton** [comment]
Problem ist, beim Überarbeiten der ArticlePreviews haben wir diese Funktion nicht mitkopiert.
Sie war vorher nur in in DensedLayout vorhanden, wir haben aber so ziemlich alles aus StandardLayout kopiert.
