### ISSUE TITLE
Anzahl ArticlePreviews erhöhen

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#39]

**Comment by BillyTheKing** [comment]
Beim Aufrufen einer Kategorie werden “Vorschauen” der Beiträge geladen. Scrollt man nach unten, werden Beiträge nachgeladen. Die Anzahl der Beiträge scheint 4 zu sein. Wir sollten die Anzahl auf 6 erhöhen, da es so aussieht, dass an der gewählten Kategorie nur 4 Beiträge hängen.

**Comment by BillyTheKing** [comment]
@ptitmouton wie viele ArticlePreviews werden auf welchen Geräten geladen

**Comment by ptitmouton** [comment]
@BillyTheKing Es werden immer 10 Beiträge vorgeladen

**Comment by BillyTheKing** [comment]
@wie0815 hast du ein Beispiel wo das Problem (noch) auftritt? Bisher kann ich weder auf Desktop noch Mobil festellen, dass zu wenige Beitragsvorschauen vorgeladen werden.

**Comment by wie0815** [comment]
Nein. Das Problem wurde schon vor Monaten behoben.
