### ISSUE TITLE
einheitlicher Style für Toolbar

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#51]
Toolbars bsp. Admin-Bereich Nutzerübersicht & Gruppenübersicht sollten eine einheitliche Komponente bekommen.

**Comment by ptitmouton** [comment]
Eventuell sollte die Toolbar im Beitrag-Bearbeiten-Modus die Komponente auch benutzen

**Comment by ptitmouton** [comment]
@BillyTheKing hat das angefangen https://github.com/lotta-schule/web/pull/117 
Ich soll das jetzt fertig machen. Kann aber noch nicht sagen wann ich dazu komme.
