### ISSUE TITLE
Admin-Bereich: Das erfolgreiche Bearbeiten einer Gruppe sollte eine Erfolgsmeldung anzeigen

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#61]
### Bug-Beschreibung

Öffnet man ein Pop-Up-Fenster einer "Gruppe" kann man Änderungen vornehmen. Lotta übernimmt diese Änderungen zuverlässig, doch wird dem Admin die Änderungen im aktuell geöffneten Fenster nicht angezeigt. Der Bug betrifft alle Lotta!

Problem: Der Admin unseres Kunden in Radebeul hat einer Gruppe ohne es zu merken universelle Administratorenrechte zugeteilt. 

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/admin/users/groups

### Gerätekategorie

Trifft hier nicht zu

**Comment by BillyTheKing** [comment]
@wie0815 Das ist kein Bug. An dieser Stelle brauchen wir eine Erfolgsmeldung/Bestätigungsmeldung ggf. zusätzlich mit einer Button-Änderung (färbt sich grün und ein Häkchen wird sichtbar). Das steht auf der Agenda für 4.2

**Comment by ptitmouton** [comment]
@BillyTheKing ich übernehme das Mal, ich denke alleine hättest du es auch nicht hinbekommen. 

Wenn #113 fertig ist sollte das denke ich mit überschaubarem Aufwand zu bewerkstelligen sein
