### ISSUE TITLE
staging: Dateiupload fehlerhaft

### ISSUE THREAD

**Issue by BillyTheKing** [lotta-schule/web#62]
Bei Staging funktioniert der Dateiupload nicht ordnungsgemäß. Bspw: angemeldet als Admin auf staging.info.lotta.schule:

Direkt nach dem Auswählen der hochzuladenden Datei, erscheint im Dateibrowser neben dem Loading-Circle ein Badge mit einem Ausrufezeichen. Ein Klick darauf öffnet den Dialog "XX Dateien werden hochgeladen" mit der Fehlermeldung "Du musst angemeldet sein um das zu tun." unter der betreffenden Datei. Selbige Fehlermeldung ist auch in der Konsole zu finden, obwohl man als Nutzer ja angemeldet ist.

Liegt eventuell an der Staging Umgebung(?)

**Comment by ptitmouton** [comment]
Gut gesehen.
Problem ist in 0fbd228f12476f3d416c49110c11040a6aeeb5c6 entstanden
