### ISSUE TITLE
[Bug]: Audio- und Videomodule spielen keine neuen Dateien ab

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#66]
### Bug-Beschreibung

Eine Audiofile (mp3) wurde nach Ehrenberg hochgeladen und in einem Beitrag über das Audiomodul verlinkt.
Die Datei wurde ordnungsgemäß im Dateibrowser abgelegt.
Im Beitrag https://ehrenberg-gymnasium.de/a/4503-mandm-SORGENTELEFON Wird der Audiofile nicht geladen. Anzeige 0:00 Minuten.

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/a/4503-mandm-SORGENTELEFON

### Gerätekategorie

Trifft hier nicht zu

**Comment by ptitmouton** [comment]
@BillyTheKing ich übernehme das ausnahmsweise direkt

**Comment by ptitmouton** [comment]
Wie man im coconut-Dashboard gut sehen kann gibt es Fehler beim Upload von Coconut zu ionos.
Ich werde aus dem Fehler gerade nicht schlau und habe eine Supportanfrage an Coconut gesendet.

**Comment by techotline** [comment]
@ptitmouton kann das Problem zeitnah behoben werden oder sind längere Ausfallzeiten zu erwarten? LG

**Comment by ptitmouton** [comment]
Für neu hochgeladene Dateien sind Umwandlungen nun wieder verfügbar.

Fehler, Lösung und Konsequenzen sind intern besprochen worden.

Ich schließe das Ticket.
