### ISSUE TITLE
[Bug] Standard-Theme für neue Lottas hat schlecht lesbare Schriftfarbe für die Navigation

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#70]
### Bug-Beschreibung

Nach dem Neuanlagen eines Lottas werden die Menüpunkte in einer Farbe dargestellt, die kaum sichtbar ist.
<img width="1302" alt="Bildschirmfoto 2023-12-08 um 19 07 46" src="https://github.com/lotta-schule/web/assets/143288974/87a29bb8-41fe-4542-a907-1779619d2afe">

### Link zur Seite, auf der das Problem aufgefallen ist

https://23-12-schule.staging.lotta.schule

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@BillyTheKing 
Wir haben hier zwei keys im Theme die dasselbe zu machen scheinen: `navigationColor` und `navigationContrastTextColor`.
Kommt mir ehrlich gesagt so vor als könnten wir eins davon löschen.

Ich kümmere mich drum
