### ISSUE TITLE
Kategorie erstellen: Darstellungsfehler Gruppenauswahl

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#71]
### Bug-Beschreibung

Eine neue Kategorie wurde erstellt. ok
Beim Einstellen der Sichtbarkeit der Kategorie für eine Gruppe wurde die Gruppe "**Lehrer**" ausgewählt.
Das Häkchen bei "für alle sichtbar ist verschwunden". Die Sichtbarkeit für Lehrer wurde also übernommen, doch ist das nicht sichtbar! (vgl Bildschirmfoto).
<img width="1279" alt="Bildschirmfoto 2023-12-08 um 19 19 04" src="https://github.com/lotta-schule/web/assets/143288974/e78ade0f-c903-4c84-b440-521f2776cce7">

### Link zur Seite, auf der das Problem aufgefallen ist

https://23-12-schule.staging.lotta.schule/admin/categories/list

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Siehe #74
