### ISSUE TITLE
Marginale: Gruppenauswahl mit Darstellungsfehlern

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#73]
### Bug-Beschreibung

vgl. #71 

1. eine Kalendermarginale wurde erstellt
2. Sichtbarkeit für die Gruppe "Lehrer" eingestellt (... wurde übernommen, nur durch fehlendes Häkchen "für alle sichtbar" bemerkbar)
3. erst bei der Eingabe der Kaalenderadresse erscheint das Pop-Up "Lehrer" und überlagert den Text "Link zu einer ..." (vgl. Bildschirmfoto)
4. 
<img width="944" alt="Bildschirmfoto 2023-12-08 um 19 39 55" src="https://github.com/lotta-schule/web/assets/143288974/288eb2ff-cc71-4b70-8f2a-333c4e832ac2">

### Link zur Seite, auf der das Problem aufgefallen ist

https://23-12-schule.staging.lotta.schule/admin/categories/widgets

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Siehe #74
