### ISSUE TITLE
Beitragserstellung: Gruppenauswahl Darstellungsfehler

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#74]
### Bug-Beschreibung

vgl. #71 
vgl.#73
Bei der Erstellung und/oder Bearbeitung von Beiträgen ist die Gruppenauswahl im Fenster "Beitragseinstellungen" fehlerhaft.
Gewählte Gruppen erscheinen außerhalb des "Bereiches" für Bearbeitung! (vgl. Bildschirmfoto)
<img width="671" alt="Bildschirmfoto 2023-12-08 um 20 02 51" src="https://github.com/lotta-schule/web/assets/143288974/a7f66ba5-1290-4bc4-a66f-2ff872e40317">

### Link zur Seite, auf der das Problem aufgefallen ist

https://23-12-schule.staging.lotta.schule/a/4-Testbeitrag-No.1/edit

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
@BillyTheKing Du hast hier für die Einträge für die GroupSelect-Komponente ein Bisschen etwas seltsames getan:
https://github.com/lotta-schule/web/commit/8d0a3d18cc50f61f85d91252456bfd4572c20ca3

In der Datei packages/webapp/src/shared/edit/GroupSelect.module.scss

Bin mir nicht sicher was du erreich wolltest aber so gehen alle Gruppenauswahlboxen kaputt.

Hätte ich im Code-Review sehen sollen, ich mache die Änderung rückgängig.
