### ISSUE TITLE
Feedbackfunktion von Nutzern mit Bug

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#75]
### Bug-Beschreibung

1. Feedbackfenster wurde geöffnet
2. Alle Eintragungen vorgenommen
3. Nach dem Klick auf "Feedback an Administrator senden" erscheint eine Fehlermeldung (siehe Bildschirmfoto)

<img width="715" alt="Bildschirmfoto 2023-12-08 um 20 32 05" src="https://github.com/lotta-schule/web/assets/143288974/e35c03ca-c6d2-42b1-8d9c-1ca10245556d">

### Link zur Seite, auf der das Problem aufgefallen ist

https://23-12-schule.staging.lotta.schule

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by wie0815** [comment]
Der gleiche Fehler tritt auch auf, wenn Administratoren an uns (Admins von Lotta) Feedback senden möchten!

**Comment by ptitmouton** [comment]
Das Deployment der Backend-Funktion war nicht erfolgreich gewesen so dass die Funktion nicht bereitstand (https://github.com/lotta-schule/core/actions/runs/7120508717/job/19387898849)
