### ISSUE TITLE
[BUG] Dateiverwaltung: Upload-Button erhält Scrollbalken auf Desktop-Safari

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#76]
### Bug-Beschreibung

Überall wo das Symbol Upload angezeigt wird, ist unter dem Symbol ein horizontaler Scrollbalken sichtbar (siehe Bildschirmfoto)
<img width="175" alt="Bildschirmfoto 2023-12-08 um 20 39 24" src="https://github.com/lotta-schule/web/assets/143288974/799c46fd-1aae-4b4d-bc47-453cffc7d345">

### Link zur Seite, auf der das Problem aufgefallen ist

https://23-12-schule.staging.lotta.schule/profile/files

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Sorry für das Durcheinander, konnte es jetzt doch nachstellen.

Problem ist ausschließlich in Safari vorhanden und vermutlich schon länger da ...
