### ISSUE TITLE
[Feature]: Zusätzliche Theme-Farbe "navigation-contrast-text-color" einführen und für unterlegte Buttons in der ersten Hauptnavigation verwenden

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#81]
### Bug-Beschreibung

Auf mobilen Geräten wird das Hamburger-Menü-Symbol in einer anderen Farbe dargestellt als die Menüpunkte. Somit kann es zu Darstellungsproblemen kommen.
Das Bildschirmfoto zeigt die Seite des Ehrenberg-Gymnasiums. Da die Menüleiste fast schwarz ist, ist das Hamburger-Menü-Symbol nicht mehr zu sehen.
![IMG_4624](https://github.com/lotta-schule/web/assets/143288974/74ea5c7d-1795-4e5b-9466-3bea73f56b7c)

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

**Comment by techotline** [comment]
Admin-Bereich "DARSTELLUNG":
Einstellung ‹Text (Farbe für Text)› ist mit dem Hamburger-Menü verknüpft, weshalb diese Problem auftritt. Ändert man die Farbe auf Weiß, so verschwindet der Anmeldebereich (Registrieren | Anmelden | Suche) für andere Geräte wie iPad oder Mac.

**Comment by ptitmouton** [comment]
Hotfix eingespielt in Lotta 4.1.4 (https://github.com/lotta-schule/web/commit/9585fa3a2feabf2ce6d81c17dce7bb77c59ad7a2)

Textfarbe für die NavigationButtons ist im Moment `--var(--lotta-contrast-text-color)`.
Ist das wirklich so sinnvoll @BillyTheKing ; War eine zusätzliche Variable `--var(--lotta-navigation-contrast-text-color)` nicht vielleicht doch die bessere Wahl?
`--var(--lotta-contrast-text-color)` kommt mir hier falsch vor: Was ist wenn jemand eine gelbe Navigation möchte?
Eventuell könnte man ja navigation-contrast-text-color einfach auf contrast-text-color defaulten lassen.

Ich lasse es als Ticket offen und weise es 4.2 zu. Ist für mich als Bug gefixt aber grundsätzlich ungeklärt.

**Comment by BillyTheKing** [comment]
@ptitmouton das Einführen einer zusätzlichen Variable für die Textfarbe der Navbar halte ich für auch für sinnvoll.
