### ISSUE TITLE
[Feature]: Feedback-Bereich: Löschen erledigter Feedbackmeldungen ermöglichen

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#82]
Feedback wurde beantwortet und ist damit erledigt.
Hier sollten wir eine Möglichkeit einfügen, Nachrichten zu löschen.

**Comment by wie0815** [comment]
Frage: Hattet Ihr @BillyTheKing @ptitmouton nicht auf dem Plan, dass der Admin angezeigt wird, der ein Feedback bearbeitet hat? LG

**Comment by ptitmouton** [comment]
Feedback kann momentan nicht gelöscht werden. Das erscheint mir sinnvoll, ich nehm das mal für 4.2 auf @BillyTheKing 

Wenn Feedback beantwortet ist, ist der "beantworten"-Button deaktiviert ("ausgegraut"), wenn weitergeleitet der "weiterleiten"-Button.
Hast du dazu Verbesserungsvorschläge oder willst eine Diskussion zu diesem Thema starten, dann mach doch bitte ein separates Ticket auf und erklär dich dort. Löschen und etwas anzeigen sind völlig verschiedene Dinge.

**Comment by ptitmouton** [comment]
@BillyTheKing Kannst du hier mal bitte einen Vorschlag machen wie man das sinnvoll ins UI integrieren könnte?

**Comment by BillyTheKing** [comment]
@ptitmouton ich kümmere mich um MockUps zum Löschen von Feedback Nachrichten.

**Comment by BillyTheKing** [comment]
Bin für eine einfache Lösung, damit nicht jedes Feedback zum Löschen geöffnet werden muss. Ich finde auch, dass hier keine Akzentfarbe oder Delete-Farbe notwendig ist.

![Web – Feedback_inkl Delete@2x](https://github.com/lotta-schule/web/assets/11082197/28409efc-44ef-4535-b6b6-4cdf50bc7e67)

**Comment by techotline** [comment]
> Frage: Hattet Ihr @BillyTheKing @ptitmouton nicht auf dem Plan, dass der Admin angezeigt wird, der ein Feedback bearbeitet hat? LG

@wie0815 der Admin, welcher das Feedback bearbeitet hat, wird in der E-Mail angezeigt, die ein Nutzer nach der Beantwortung automatisch erhält.

"Der Administrator JP hat dein Feedback beantwortet." Im Anschluss folgt die Nachricht, welche der Admin optional beifügt. 

@wie0815 sozusagen könnte nach Beantworten von Feedback der Name im Adminbereich angezeigt werden, weil Button "Beantworten" sowieso "ausgegraut" ist, um nachzuvollziehen, wer den Fall geschlossen hat.

**Comment by ptitmouton** [comment]
Wir speichern nicht wer ein Feedback beantwortet hat.

Das Ziel war es explizit, das Feature vorerst so einfach wie möglich zu halten. Ich denke auch dass das im Moment ausreicht, das Feature ist funktional und für die allermeisten Use-Cases unserer Nutzer völlig ausreichend, so dass wir uns anderen Sachen widmen können.

Ich verstehe auch nicht ganz was die Antwortende Person mit dem Löschen des Feedbacks zu tun hat.

Feedbacks werden um die Funktion erweitert, gelöscht werden zu können. Darüber hinaus sehe ich die Feedback-Funktion erstmal als abgeschlossen an.
