### ISSUE TITLE
[Bug]: Suche: Menü für die Kategorie wird von Navigationsleiste überlappt

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#83]
### Bug-Beschreibung

Möchte man in der Suche eine Kategorie wählen, "springt" das aufklappende Fenster der Kategorieauswahl nach oben unterhalb der Menüleiste (vgl Bildschirmfoto).
<img width="474" alt="Bildschirmfoto 2023-12-11 um 19 40 48" src="https://github.com/lotta-schule/web/assets/143288974/5c6edf38-f821-43c0-8ec4-7abbc026cbf1">

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/search

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
z-index von Popups angepasst (10000)

f4daf028cd427b9d281147b611bfa2ce8c1d2a2b
