### ISSUE TITLE
[Bug]: Beitrag speichern: Popover-Menü verschwindet sofort nach dem Öffnen, Benutzen unmöglich

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#84]
### Bug-Beschreibung

Das Pop-up-panel springt, sobald ein Beitrag fertiggestellt ist und das SPEICHERN über das zusätzliche Auswahlfenster mit den Aktionen "_Ohne Aktualisierszeit zu ändern_" oder "_Aktualisierszeit auf Erstellszeit setzen_" aufgerufen bzw. ausgeführt  werden möchte.

Problem: https://we.tl/t-BYngmI8RPd 
Folge: wenn der Button länger als 2 sec gehalten wird, lassen sich die Aktionen erreichen:
<img width="436" alt="SC-B-Lotta-1" src="https://github.com/lotta-schule/web/assets/153733311/94057158-9f14-47e1-9744-7c105ca0053f">

Details:

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15
Platform: MacIntel
Screen: 1440x900
Window: 1440x820
DevicePixelRatio: 2
DeviceOrientation: landscape-primary

### Gerätekategorie

Laptop / Desktop (PC, Mac, Chromebook)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
#83 Ähnliches Problem mit Data-Popper.
Ich kümmere mich.

**Comment by ptitmouton** [comment]
@BillyTheKing #85 ist ein Problem mit dem z-index. Das hier scheint (mal wieder) ein webkit-Bug der nur Safari betrifft, habs gerade probiert.
Die Fehler hängen nicht (direkt) zusammen.

**Comment by ptitmouton** [comment]
Fix main und als Hotfix releast.

Wir ersetzen onPressStart durch onClick.
Die Lösung ist nicht die eleganteste, tut aber was sie soll.

197e41874aea8b762a7b783d93dfd7c1d7ea70bc
