### ISSUE TITLE
[Bug]: FEEDBACK: Nutzer erhalten keine Antwort

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#85]
### Bug-Beschreibung

Sendet ein Nutzer ein Feedback-Formular an die Administratoren ab, kann er (admins) dieses im Admin-Bereich einsehen und ggf. beantworten. Derzeit erhalten Nutzer jedoch keine E-Mail, sobald dieser eine Nachricht (Antwort) verfasst und abgesendet hat. Mehrere Testversuche ergebnislos durchgeführt.

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
@techotline mein Test ergab selbiges Problem.

@ptitmouton Funktion Feedback Beantworten/Weiterleiten im Admin Bereich.
a) Klick auf Beantworten -> Dialog -> Klick auf "Auf Feedback Antworten" Dialog schließt sich -> keine E-Mail an Nutzer
b) Klick auf Weiterleiten -> Dialog -> Klick auf "An Lotta Entwickler weiterleiten" Dialog schließt sich -> keine E-Mail in unser einsA Postfach

**Comment by techotline** [comment]
> @techotline mein Test ergab selbiges Problem.
> 
> 
> 
> @ptitmouton Funktion Feedback Beantworten/Weiterleiten im Admin Bereich.
> 
> a) Klick auf Beantworten -> Dialog -> Klick auf "Auf Feedback Antworten" Dialog schließt sich -> keine E-Mail an Nutzer
> 
> b) Klick auf Weiterleiten -> Dialog -> Klick auf "An Lotta Entwickler weiterleiten" Dialog schließt sich -> keine E-Mail in unser einsA Postfach
> 
> 

@BillyTheKing erhaltet Ihr gesendete Nachrichten über den Dialog "Feedback an Lotta Entwickler"?

**Comment by ptitmouton** [comment]
Es war eine falsche Empfängeradresse angegeben.
Hätte im Test auffallen sollen, hier haben rächt sich der schnelle Release der Feedbackfunktion.

https://github.com/lotta-schule/core/commit/d2719df132a63a1348104643bfbfa729dff21bc2 wird bis morgen als Hotfix veröffentlicht
