### ISSUE TITLE
[Bug]: TAGs werden nicht getrennt dargestellt

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#88]
### Bug-Beschreibung

Wendet ein Nutzer für seinen Beitrag mehr als ein neuen Tag an, dann passiert folgender Fehler.
SC: 
<img width="843" alt="bug-Lotta-tag" src="https://github.com/lotta-schule/web/assets/153733311/ed7be92e-d57c-48c3-9f5b-4e4701c28732">

Folge: _Die Tags werden aneinander gereiht und nicht mehr getrennt in dem Pop-up abgelegt._

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
@techotline ich kann deine Fehlermerldung leider nicht nachstellen. 
Um es genau nachvollziehen und prüfen zu können, würde ich dich bitten, den Klickweg noch mal kleinschrittig und vollständig aufzuschreiben. Danke.

**Comment by techotline** [comment]
> @techotline ich kann deine Fehlermerldung leider nicht nachstellen. Um es genau nachvollziehen und prüfen zu können, würde ich dich bitten, den Klickweg noch mal kleinschrittig und vollständig aufzuschreiben. Danke.

Ich werde zeitnah einen Kommentar hinterlassen. An dieser Stelle ist es umständlicher, das Problem präzise zu erklären.
