### ISSUE TITLE
[Vorschlag]: Avatar-Group optimize

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#89]
### Bug-Beschreibung

Hat ein Beitrag mehr als 3 User, dann wird ein 

> number-circle

> .Bsp.: "+ 5"

SC: 
<img width="946" alt="style-Lotta-Beitrag" src="https://github.com/lotta-schule/web/assets/153733311/84261bcd-64be-4f81-8bbe-0ff3f3421472">

angezeigt. Das sieht nicht schön aus.

- Frage: Wie könnte man alle Nutzer abbilden oder die Vorschau verbessern, wenn ein Beitrag z.B. 6 Autoren hat?
- Idee: in den Desktop-Versionen ist der notwendige Platz vorhanden, alle Avatars dazustellen. Ich würde es mir wünschen. Bei mehreren durch "+x" verdeckten Autoren sollte bei einem Klick auf das "+x" eine Auflistung der verdeckten Autoren erscheinen.

SC: 
<img width="1249" alt="sytlye-Lotta-Beitrag-3" src="https://github.com/lotta-schule/web/assets/153733311/dcbedfce-ec44-4317-b83d-9c804291da90">
<img width="1105" alt="style-Lotta-Beitrag-2" src="https://github.com/lotta-schule/web/assets/153733311/81cb743c-8595-4582-97b0-468cf5ce24ea">

### Link zur Seite, auf der das Problem aufgefallen ist

https://ehrenberg-gymnasium.de/a/4086-kPro9-in-Chemnitz

### Gerätekategorie

Trifft hier nicht zu

**Comment by BillyTheKing** [comment]
Die aktuelle Komponente "AvatarGroup" wird aktuell an jeder Stelle auf Lotta eingesetzt, bei welcher mehrere Avatare angezeigt werden müssen. Also bsp. Beiträge, Beitragsvorschauen (kompakt, zweispaltig, etc.), Mobil, Desktop usw.
Der Aufwand wäre also an dieser Stelle für uns zwei Entwickler zu groß, für diese doch kleine Verbesserung. Wir sind jedoch dabei die Anzeige der Nutzer über die Avatare (Ticket #109 ) anzupassen und mehr Informationen anzuzeigen (Ticket #112 ).
