### ISSUE TITLE
[Vorschlag]: Links zum Administrationsbereich sollten mit Badge markiert sein, wenn unbearbeitetes Feedback vorliegt

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#91]
### Feature-Beschreibung

Sollten Nutzer im Laufe der Zeit Feedback verfassen und diese an die Admins absenden, könnte dieser benachrichtigt werden.

Problem: zeitliche Prozedur, da neues Feedback nicht angekündigt wird. Somit "tägliches" bzw. regelmässiges Überprüfen nicht mehr notwendig.
Idee: Marker (Badge) im Pop-up-Fenster (vgl. Nachrichten)

SC: 
<img width="311" alt="feature-Lotta-1" src="https://github.com/lotta-schule/web/assets/153733311/456b9004-0eda-426a-b01b-b9f64949ebea"> 

### Gerätekategorie

Trifft hier nicht zu

**Comment by BillyTheKing** [comment]
@techotline an der vorgeschlagenen Stelle keine Option, da diese Stelle nur zum Einreichen eines Feedbacks führt, jedoch nicht in den Admin Bereich.

Möglichkeit: Badge-Icon mit neuen Feedbacks A) Am Navigationspunkt Adminbereich oder B) im Adminbereich am Icon für Feedback oder C) an beiden Stellen.

@wie0815 @ptitmouton

**Comment by techotline** [comment]
@BillyTheKing AW

"an der vorgeschlagenen Stelle keine Option" (...) gut erklärt. Ich hätte mich klarer ausdrücken und mein Ticket präziser erklären müssen. Danke!

"Möglichkeit: Badge-Icon mit neuen Feedbacks A) Am Navigationspunkt Adminbereich oder B) im Adminbereich am Icon für Feedback oder C) an beiden Stellen." Ein Badge-Icon ist die Idee, welche ich ursprünglich hervorbringen wollte. An den markanten Ankerpunkten ein nützliches Merkmal.

Meiner Meinung nach Variante C)! LG
