### ISSUE TITLE
Feedback sendet Fehler und lässt sich nicht mehr steuern

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#92]
### Bug-Beschreibung

Kam gerade per Chat (siehe Bildschirmfotos):
![IMG_4648](https://github.com/lotta-schule/web/assets/143288974/525d1e6d-ff42-4598-a2b9-03b7260ff19e)
<img width="1423" alt="Bildschirmfoto 2023-12-17 um 17 17 43" src="https://github.com/lotta-schule/web/assets/143288974/17629d1a-e55c-42ff-8c8a-e1cb14f17e34">

### Link zur Seite, auf der das Problem aufgefallen ist

schnappschussfaenger.de/admin/system/feedback

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
@wie0815 das ist eine sehr dürftige Bug Meldung. Ich konnte den Fehler jedoch nachstellen.
Es ist kein Browser abhängier Bug.

**Lösung vorerst:** Seite neu laden, dann funktioniert es wie gehabt.

Ich erstelle zeitnah ein Ticket.

**Comment by BillyTheKing** [comment]
@ptitmouton 
Konnte den Bug wie beschrieben nachstellen: 
Klickt man im Adminbereich auf "Feedback" erscheint die Fehlermeldung `Application Error:` . Lädt man die Seit neu, gelangt man zum Feedback-Seite im Admin-Bereich.

**Comment by ptitmouton** [comment]
Fix in Hotfix 4.1.5 https://github.com/lotta-schule/web/commit/2b94f6e2a1583f082864d8473d6fae9eaf25a963
Plausible-Integration hat Problem verursacht
