### ISSUE TITLE
[Style] Breakout of text in feedback mode (Inhalt bricht über Begrenzung aus)

### ISSUE THREAD

**Issue by techotline** [lotta-schule/web#93]
### Bug-Beschreibung

Die aktuellen Ereignisse zeigen, wie der Inhalt des Feedback-Bereiches mit dem Seitenverhältnis überlagert bzw. überlappt (overlay). Der nebenstehende Freitext bricht aus dem Format aus.

Ich verdeutliche den Fehler anhand des Screenshots: 

![IMG_5544](https://github.com/lotta-schule/web/assets/153733311/d8631066-bcfa-49b5-9168-d07b79c69950)

system: User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1
Platform: iPhone
Screen: 393x852
Window: 393x659
DevicePixelRatio: 3
DeviceOrientation: portrait-primary

### Link zur Seite, auf der das Problem aufgefallen ist

https://schnappschussfaenger.de/admin/system/feedback

### Gerätekategorie

Mobiltelefon (iPhone / Android-Telefon)

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by BillyTheKing** [comment]
Derzeit gibt es den Feedback Bereich nur für Desktop-/Tablet-User.
Die responsive Variante wird in der nächsten Lotta Version mitgeliefert.

**Comment by ptitmouton** [comment]
Eventuell können wir das gleich mit #100 zusammen erledigen?
Würde für SplitView eine Option ergänzen, dass die Navigation rechts und der Content links ist. Dann könnte man das analog zu den aktuellen SplitViews auf der Nachrichtenseite / Admin-Gruppen-Seite gestalten, nur dass es eben rechts aufklappt. 

Was meinst du @BillyTheKing ? Wäre vielleicht die pragmatischste Lösung

**Comment by ptitmouton** [comment]
Ist in #141 erledigt
