### ISSUE TITLE
Coconut: Videoumwandlung zeigt Fehler

### ISSUE THREAD

**Issue by wie0815** [lotta-schule/web#94]
### Bug-Beschreibung

Neue Video- und Audiodateien werden aktuell nicht angezeigt. Das Problem ist bekannt. @ptitmouton meinte, dass er keinen Fehler finden kann. Ich habe ein (für uns) wichtigen Film hochgeladen und parallel in Coconut nachgesehen, ob die Umwandlung stattfindet. Coconut zeigt 3 Fehler an. Siehe Bildschirmfoto.
<img width="1026" alt="Bildschirmfoto 2023-12-18 um 07 11 09" src="https://github.com/lotta-schule/web/assets/143288974/f72586ef-a9c3-4a22-a47b-7fd38b0463de">

### Link zur Seite, auf der das Problem aufgefallen ist

https://inklusivleben.jetzt/a/212-2023-12-Sachsenspiegel

### Gerätekategorie

Trifft hier nicht zu

### In welchem Browser ist das Problem aufgetreten

Safari

**Comment by ptitmouton** [comment]
Der Fehelr ist doch bekannt. Was soll das bringen hier 1000 Tickets zu bekannten Fehlern zu erstellen? Haben wir noch nicht genug Tickets die wir sortieren und bearbeiten muessen?

**Comment by ptitmouton** [comment]
See #66

**Comment by wie0815** [comment]
@ptitmouton Sorry!
